converter/dicom-cast/docs/authentication.md
docs/how-to-guides/configure-dicom-server-settings.md
docs/how-to-guides/sync-dicom-metadata-to-fhir.md

Adding example end to end flow for how to enable auth for dicom cast with managed identity
Addresses [AB#76021](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76021)
[AB#75894](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/75894)

adding more instructions for enabling dicom cast

---

GeoPol.xml

Typo with file to exclude from GeoPol scans

GeoPolitical Update: Fix for SyntaxFix into master branch

---

docs/tutorials/use-dicom-web-standard-apis-with-c#.md

Add in documentation to C# tutorial on how to use response.
https://microsofthealth.visualstudio.com/Health/_workitems/edit/76262

C# tutorial use retrieved instances

---

docs/quickstarts/deploy-dicom-cast.md

Fixes issue #361
Reimplement update Moira did which wasn't committed to master
Addresses #361 
Viewed in GitHub

Update deploy-dicom-cast with corrected URL

---

docs/development/setup.md

Clarify dev usage instructions for fiddler.
N/A
N/A

update fiddler usage instructions

---

src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj
src/Microsoft.Health.Dicom.Metadata/Microsoft.Health.Dicom.Metadata.csproj

Updating to the latest shared components library to support MI for blob storage
[User Story 76205](https://microsofthealth.visualstudio.com/Health/_workitems/edit/76205)

Updating to latest shared components library to support MI for blob storage

---

docs/concepts/dicom.md

"Medical Imaging Service for DICOM" -> "Medical Imaging Server for DICOM"

Small typo in dicom.md

---

docs/resources/faq.md

Adding more Qs to FAQ, based on some customer questions
[AB#76432](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76432)
Previewed in VSCode

adding more questions to faq

---

docs/development/setup.md

Fixing link to download DCM files
Customer notified us of issue of broken link

Update link to dcms in setup.md

---

docs/tutorials/use-the-medical-imaging-server-apis.md

Fixing some broken links I found when reading a doc.
Clicked on the links :)

Fix broken links in docs

---

docs/development/setup.md

add .net sdk install link

---

tools/dicom-web-electron/THIRDPARTYNOTICES.MD
tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json

Updates `electron` and `electron-builder` to latest versions.
Addresses [AB#77158](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/77158).
Manual testing of the electron app.

Updates to electron components.

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Microsoft.Health.DicomCast.Core.csproj
src/Microsoft.Health.Dicom.Client/Microsoft.Health.Dicom.Client.csproj
src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/DicomDatasetExtensionsTests.cs
src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
src/Microsoft.Health.Dicom.Metadata/Microsoft.Health.Dicom.Metadata.csproj
src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomItemCollectionEqualityComparer.cs
src/Microsoft.Health.Dicom.Tests.Common/Microsoft.Health.Dicom.Tests.Common.csproj
test/Microsoft.Health.Dicom.Tests.Integration/Features/TranscoderTests.cs
tools/scale-testing/Common/Common.csproj

Update version of fo-dicom from 4.0.6 to 4.0.7. Updated test cases affected by the changes.
Need to validate that this fo-dicom version fixes the following bugs:
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=76354
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=76355
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=76288
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=75334
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=75008
These are the relevant bugs that I found that were dependent on this fo-dicom release, please update if I …

Update fo-dicom 4.0.6 -> 4.0.7

---

.github/workflows/CreateRelease.ps1
.github/workflows/log.txt
.github/workflows/oss-release.yml

GitHub action that runs every Tuesday to trigger a powershell script that approves and generates latest release.
[User Story 76752](https://microsofthealth.visualstudio.com/Health/_workitems/edit/76752)

Adding in a Github action to create a release.

---

.github/workflows/oss-release.yml

Fixing syntax bug.
[User Story 76752](https://microsofthealth.visualstudio.com/Health/_workitems/edit/76752)

Updating release workflow syntax

---

docs/tutorials/use-dicom-web-standard-apis-with-c#.md

Small update to C# tutorial due to latest changes in DicomWebClient.

C# tutorial update for DicomWebClient changes

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Blob/Microsoft.Health.DicomCast.Blob.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Microsoft.Health.DicomCast.Core.UnitTests.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Microsoft.Health.DicomCast.Core.csproj
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj
src/Microsoft.Health.Dicom.Api/Modules/AuditModule.cs
src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj
src/Microsoft.Health.Dicom.Client/Microsoft.Health.Dicom.Client.csproj
src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
src/Microsoft.Health.Dicom.Metadata/Microsoft.Health.Dicom.Metadata.csproj
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Microsoft.Health.Dicom.SqlServer.UnitTests.csproj
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj
test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj

Update healthcare-shared-components version to latest version and also FHIR.

Update healthcare-shared-components version

---

docs/how-to-guides/enable-authentication-with-tokens.md
docs/how-to-guides/sync-dicom-metadata-to-fhir.md

Update docs for how to use AAD v2 and also to verify using managed identity to set up dicom-server, dicom-cast, and fhir.

AAD V2 and Dicom to Fhir doc updates

---

docs/quickstarts/deploy-dicom-cast.md

Fixing links to deploy arm templates 
[AB#76829](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76829)

Update links in deploy-dicom-cast.md

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs
src/Microsoft.Health.Dicom.Api/Controllers/ChangeFeedController.cs
src/Microsoft.Health.Dicom.Api/Controllers/DeleteController.cs
src/Microsoft.Health.Dicom.Api/Controllers/QueryController.cs
src/Microsoft.Health.Dicom.Api/Controllers/RetrieveController.cs
src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs
src/Microsoft.Health.Dicom.Core/Features/Delete/DeleteService.cs
src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs
src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveTransferSyntaxHandler.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexSchema.cs

Update logging statements.
[AB#77458](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/77458)

Update logging structure

---

samples/templates/dicomcast-quick-deploy.json

Removing app insights setting - I think my latest changes didn't get incorporated into original PR
[AB#76829](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76829)

Update parameters in  dicomcast-quick-deploy.json

---

.github/workflows/oss-release.yml

Adding in a manual trigger to oss-release
[AB#76752](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76752)

Adding manual trigger to oss-release.

---

README.md

Adding link to performance guidance in readme

Update README.md to include performance guidance link

---

.github/workflows/oss-release.yml

Updating release so it can access powershell file

---

.github/workflows/oss-release.yml

adding step name for uploading log file

---

.github/workflows/CreateRelease.ps1

re-add content type header

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelperTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/FhirTransactionConstants.cs

Update the the format specifier to match c# documentation and fixed the test cases to ensure proper testing. In previous version the format specifier was incorrect and the test case was generated non-statically using the specifier so the bug was not caught.
AB#77746
Updated the unit tests.

Fix bug for TimezoneOffset bug

---

docs/concepts/dicom-cast.md

Update document for Accession Number change
The Property column is FHIR path (http://hl7.org/fhirpath/)
Addresses AB#77787

Add Accession Number

---

.github/workflows/CreateRelease.ps1
.github/workflows/oss-release.yml

Minor Changes to Formatting

---

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql

Adding in 2.sql to use for custom tag schema changes. Currently, the schema is equivalent to existing schema.
AB#78128

Adding in a forked version of sql schema

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/DicomCastWorker.cs

Update so that unhandled errors from ExecuteAsync method from dicom-cast worker cause the application to stop and shut down. 
AB#77856
Tested by running locally to make sure that on unhandled error shuts down entire application.

Dicom-Cast update error handling to stop application

---

src/Microsoft.Health.Dicom.Web/appsettings.Development.json
src/Microsoft.Health.Dicom.Web/appsettings.json

Adding in a value to configuration files that is accessible where necessary to guard code under development for custom query tags.
AB#78137

Adding feature flag for custom query tags

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/DicomCastWorkerTests.cs

Remove a flaky test that fails on CI pipeline.
Added bug AB#78349

[Dicom-Cast] Remove Flaky test

---

tools/dicom-web-electron/THIRDPARTYNOTICES.MD
tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json

Updates axios from 0.21.0 to 0.21.1
Addresses AB#78337.
Manually ran the electron uploader tool.

Update axios 0.21.1

---

src/Microsoft.Health.Dicom.Api/Controllers/CustomTagController.cs
src/Microsoft.Health.Dicom.Api/Features/Routing/KnownRoutes.cs
src/Microsoft.Health.Dicom.Core/Extensions/DicomMediatorExtensions.cs
src/Microsoft.Health.Dicom.Core/Features/Audit/AuditEventSubType.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagEntry.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagLevel.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagStatus.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/AddCustomTagRequest.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/AddCustomTagResponse.cs

Add controller for custom tag
Addresses AB#78129

Add CustomTagController

---

.github/workflows/build-docker.yml

build docker files on PRs
AB#78628
This PR will test

build docker files on PRs

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/CustomTagServiceTests.cs
src/Microsoft.Health.Dicom.Core/Extensions/DicomTagExtensions.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/AddCustomTagHandler.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagEntry.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagService.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/ICustomTagEntryValidator.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/ICustomTagService.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/ICustomTagStore.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/IReindexJob.cs

Add service and handler for adding custom tag
Addresses AB#78143

Service and Handler for add custom tag

---

src/Microsoft.Health.Dicom.Api/Controllers/CustomTagController.cs
src/Microsoft.Health.Dicom.Api/Features/Routing/KnownActionParameterNames.cs
src/Microsoft.Health.Dicom.Api/Features/Routing/KnownRoutes.cs
src/Microsoft.Health.Dicom.Core/Extensions/DicomMediatorExtensions.cs
src/Microsoft.Health.Dicom.Core/Features/Audit/AuditEventSubType.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/GetAllCustomTagsRequest.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/GetAllCustomTagsResponse.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/GetCustomTagRequest.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/GetCustomTagResponse.cs

Adding support to get custom tags to controller.
[AB#78173](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78173)
[AB#78174](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78174)

Adding get custom tag to controller

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Common/DicomTagParserTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/CustomTagEntryValidatorTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/CustomTagServiceTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/DicomTagExtensions.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryParserTests.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Exceptions/CustomTagEntryValidationException.cs
src/Microsoft.Health.Dicom.Core/Features/Common/DicomTagParser.cs
src/Microsoft.Health.Dicom.Core/Features/Common/IDicomTagParser.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagEntryValidator.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagService.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagStoreEntry.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/ICustomTagEntryValidator.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/IReindexJob.cs
src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.cs
src/Microsoft.Health.Dicom.Core/Messages/CustomTag/AddCustomTagResponse.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs

Add CustomTagEntryValidator
Addresses [AB#78138](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78138)
Unit tests pass

Add CustomTagEntryValidator

---

samples/templates/dicomcast-fhir-dicom-azuredeploy.json
samples/templates/dicomcast-quick-deploy.json

DICOM Cast deployment (with FHIR) was failing if enableexport was set to true. 
- Issue was that it only works if you are owner of subscription, not just contributor 
Also, links and parameters were broken since fhir updated arm template 
[AB#77700](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/77700)
Deployed to azure portal (tested all fhir variables)

DICOM Cast Quick Deployment Fixes 

---

.github/workflows/build-docker.yml
README.md
build/.vsts-ci.yml
docs/quickstarts/deploy-dicom-cast.md
docs/resources/Conformance-as-Postman.postman_collection.json
samples/templates/dicomcast-fhir-dicom-azuredeploy.json
samples/templates/dicomcast-quick-deploy.json
tools/dicom-web-electron/readme.md

Updates various references from `master` to `main` after the source branch update.
Tests continue to pass.

Updating references of master to main

---

tools/scale-testing/ReadMe.md

Update Minor error to trigger release

---

.github/workflows/build-docker.yml
.github/workflows/test-docker.ps1
build/docker/Dockerfile
converter/dicom-cast/build/docker/Dockerfile
samples/docker/docker-compose.yaml

adds a test for dicom-api & dicom-cast containers
fixes dicom-api & dicom-cast containers
addresses [AB#79151](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79151)
github build action is the test

have sniff test for dicom-api & dicom-cast containers

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/Models/Entities/HealthEntity.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/Models/Entities/IntransientEntity.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/Models/Entities/RetryableEntity.cs

Updated the TableEntities to match the requirements define here (https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet#define-the-entity). They need to have setters for all public fields  and a constructor without any parameters.

[Dicom-Cast] Update Table Storage Entities

---

nuget.config

Remove obsolete elements from NuGet config
N/A
Build pipelines should still succeed

Update NuGet Config

---

README.md

Fixing architecture diagram
Fixing architecture diagram image in readme file 
[AB#79270](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79270)

Update README.md Arch Image

---

README.md

Change the deploy to azure buttons to use the latest arm templates in the main branch of the repo.

Update deploy to azure buttons to use arm templates from main branch

---

converter/dicom-cast/samples/templates/default-azuredeploy.json
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelperTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/Patient/PatientSynchronizerTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/FeatureConfiguration.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyInstancePropertySynchronizer.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelper.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPropertySynchronizer.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudySeriesPropertySynchronizer.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/Patient/PatientSynchronizer.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.json
docs/concepts/dicom-cast.md
docs/quickstarts/deploy-dicom-cast.md

Update the documentation for dicom cast to talk about partial validation and table storage.  
Also change the feature flag to be of the format @KnicKnic suggested and made neccessary code changes.
Update the deploy to azure button in another location to use the one from the main branch.

[Dicom-Cast] Update PartialValidation feature flag and documentation

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/GetCustomTagsServiceTests.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagEntry.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/ICustomTagStore.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/SqlCustomTagStore.cs

Fix Build failure and remove useless methods

Fix Build failure and remove useless methods

---

build/.vsts-ci.yml

This PR adds the setup of the AAD test environment to CI. This should allow any changes related to expected auth scenarios to be auto-supported in CI.
Created new CI pipeline to test the run.

Add setup AAD test environment to CI.

---

README.md
docs/development/roles.md
docs/how-to-guides/enable-authorization.md

This PR adds documentation around RBAC support.
Addresses [AB#79318](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79318)

Add authorization (RBAC) documentation

---

Directory.Build.props
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs

Updating healthcare shared components package version.

---

docs/tutorials/use-dicom-web-standard-apis-with-c#.md

Add link to public nuget feed for Dicom Web Client.
#553

Update c# tutorial with nuget information

---

README.md
build/ci-variables.yml
build/pr-variables.yml
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/ChangeFeedProcessorTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/RetryableFhirTransactionPipelineTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/RetryConfiguration.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/ExceptionStorage/IExceptionStore.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/RetryableFhirTransactionPipeline.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/WorkerModule.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.json
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableExceptionStore.cs
docs/development/roles.md
docs/how-to-guides/enable-authorization.md
docs/tutorials/use-dicom-web-standard-apis-with-c#.md

Merge from main to feature branch 
Addresses [AB#79464](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79464)
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx

Merge from main to feature branch (2/16/2021)

---

src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Exceptions/CustomTagBusyException.cs
src/Microsoft.Health.Dicom.Core/Exceptions/CustomTagNotFoundException.cs
src/Microsoft.Health.Dicom.Core/Exceptions/PreconditionFailedException.cs
src/Microsoft.Health.Dicom.SqlServer/DicomSqlServerResource.Designer.cs
src/Microsoft.Health.Dicom.SqlServer/DicomSqlServerResource.resx
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/CustomTagDataType.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/CustomTagLimit.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/SqlCustomTagStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomServerBuilderSqlServerRegistrationExtensions.cs

Implement SQLStore for DeleteCustomTag
Addresses [AB#78132](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78132)

Implement SQLStore for DeleteCustomTag

---

src/Microsoft.Health.Dicom.Client/DicomWebClient.cs
src/Microsoft.Health.Dicom.Client/DicomWebConstants.cs
src/Microsoft.Health.Dicom.Client/IDicomWebClient.cs
src/Microsoft.Health.Dicom.Client/Models/CustomTagEntry.cs
src/Microsoft.Health.Dicom.Client/Models/CustomTagLevel.cs
src/Microsoft.Health.Dicom.Web/Properties/launchSettings.json
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/CustomTagTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HttpIntegrationTestFixture.cs

Add API to DicomWebClientclient as well as End to End Tests
Addresses [AB#79717](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79717)

Add API to DicomWebClientclient as well as End to End Tests

---

Directory.Build.props
src/Microsoft.Health.Dicom.Core/Features/CustomTag/GetCustomTagsService.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs
src/Microsoft.Health.Dicom.Web/Startup.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs

Fix bug which block service to start
Addresses [AB#78174](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78174)
Locally tested with Add/Remove/Get/List custom tag

Fix bug which block service to start

---

converter/dicom-cast/samples/templates/default-azuredeploy.json
samples/templates/dicomcast-fhir-dicom-azuredeploy.json
samples/templates/dicomcast-quick-deploy.json

Update the ARM templates with the "enforceValidationOfTagValues" values for the arm templates that deploy all three of Dicom, Dicom-Cast, and FHIR.

[Dicom-Cast] Update Arm templates that deploy Dicom, Dicom-Cast, and FHIR

---

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql

@TagKey is a variable to save tagKey, so that it should be as same type as TagKey. this is a typo.

TagKey should be BIGINT

---

.github/workflows/codeql-analysis.yml

- Add CodeQL GitHub action that runs for PRs against `main`, CI, and weekly
N/A
Run the new action

Add CodeQL GitHub Action

---

src/Microsoft.Health.Dicom.Api/Controllers/CustomTagController.cs
src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Common/DicomTagParserTests.cs
src/Microsoft.Health.Dicom.Core/Features/Common/DicomTagParser.cs

Fix multiple bugs in Get/List custom tags
Addresses [AB#80037](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80037) and [AB#80038](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80038)
unit tests, locally manually tests.

Fix bugs in Get/List Custom Tags

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/GetCustomTagsServiceTests.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagStoreEntry.cs
src/Microsoft.Health.Dicom.Core/Features/Query/Model/FilterConditions/CustomTagFilterDetails.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/SqlCustomTagStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryGenerator.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.Tests.Common/Extensions/DicomTagExtensions.cs

Change TagKey column from BigInt to Int.
Addresses [AB#80090](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80090)
All test passed locally.

Change TagKey column from BigInt to Int.

---

src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Features/Common/DicomTagParser.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs

Merge from main (3/8/2021)
Addresses [AB#79464](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79464)
All automated tests pass
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HttpIntegrationTestFixture.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
src/Microsoft.Health.Dicom.Core/Features/Common/DicomTagParser.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Client/DicomWebClient.cs
Directory.Build.props

Merge from main (3/8/2021)

---

src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Query/SqlQueryGeneratorTests.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryGenerator.cs

[AB#80256](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80256)

Fixing syntax bug

---

Directory.Build.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Microsoft.Health.DicomCast.Core.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Microsoft.Health.DicomCast.TableStorage.csproj
src/Microsoft.Health.Dicom.Api.UnitTests/Microsoft.Health.Dicom.Api.UnitTests.csproj
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs
src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj
src/Microsoft.Health.Dicom.Client/Microsoft.Health.Dicom.Client.csproj
src/Microsoft.Health.Dicom.Core.UnitTests/Microsoft.Health.Dicom.Core.UnitTests.csproj
src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
src/Microsoft.Health.Dicom.Metadata/Microsoft.Health.Dicom.Metadata.csproj
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Query/SqlQueryGeneratorTests.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryGenerator.cs
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj
src/Microsoft.Health.Dicom.Web/appsettings.json
test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj
test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj
tools/scale-testing/Common/Common.csproj
tools/scale-testing/QidoFunctionApp/QidoFunctionApp.csproj
tools/scale-testing/StowFunctionApp/StowFunctionApp.csproj
tools/scale-testing/WadoFunctionApp/WadoFunctionApp.csproj
tools/scale-testing/WadoMetadataFunctionApp/WadoMetadataFunctionApp.csproj

- Reacting to the fix of https://github.com/Azure/azure-sdk-for-net/issues/12445
This allows configuring concurrency on upload
- Also had to upgrade the shared packages and Ensure that to pull the new property
- Fix issue https://github.com/microsoft/dicom-server/issues/595
[AB#80301](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80301)
Existing tests passed

Add BlobUploadOptions to Blob UploadAsync, Fix QIDO fuzzy matching

---

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/CustomTagStoreTests.cs

Change TagStatus to Deindexing when start deleting custom tag
Addresses [AB#80141](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80141)
All automation tests pass

Change TagStatus to Deindexing when start deleting custom tag

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/GetCustomTagsServiceTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/DicomQueryServiceTests.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagStoreEntry.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/SqlCustomTagStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.Tests.Common/Extensions/DicomTagExtensions.cs

Add PrivateCreator in table CustomTag
Addresses AB380424

Add PrivateCreator in table CustomTag

---

src/Microsoft.Health.Dicom.Core/Extensions/DicomDatasetExtensions.cs
src/Microsoft.Health.Dicom.Core/Features/CustomTag/CustomTagEntryValidator.cs
src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.cs
src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/AddInstanceTableValuedParametersBuilder.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/DicomTagSqlEntry.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV1.cs

Remove support to AT, DT, TM
Addresses [AB#80359](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80359)

Remove support to AT, DT, TM

---

build/package.yml
src/Microsoft.Health.Dicom.Tests.Common/Microsoft.Health.Dicom.Tests.Common.csproj

Allow test packages to be packaged and published
These will be used in PaaS repo to run E2E tests
[AB#76726](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76726)
Test are packed

allow test packages to be packaged and published

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Study.cs

Disable Flaky tests while fixing, tracked by https://microsofthealth.visualstudio.com/Health/_workitems/edit/80262
Addresses [AB#80262](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80262)

Disable Flaky tests

---

build/.vsts-ci.yml
build/.vsts-pr.yml

Fix typo in build pipelines to prevent warnings
N/A
Run pipelines without warning

Fix analyzeSecurity Variable

---

docs/how-to-guides/extended-query-tags.md
docs/resources/extended-query-tags.md

[AB#80133](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80133)

Adding documentation for extended query tags

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryParserTests.cs
src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.cs

[AB#80693](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80693)

Fix fuzzy matching for extended query tags

---

src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/DeleteExtendedQueryTagHandler.cs
src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetAllExtendedQueryTagsHandler.cs
src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagHandler.cs

Rbac support for extended query tag Apis
Addresses [AB#80084](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80084)
AddExtendedQueryTag Api already has Rbac support

Rbac support for extended query tag Apis

---

src/Microsoft.Health.Dicom.Api.UnitTests/Features/HealthCheck/HealthCheckCachingTests.cs
src/Microsoft.Health.Dicom.Blob/Registration/DicomServerBuilderBlobRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Metadata/Registration/DicomServerBuilderMetadataRegistrationExtensions.cs

This PR updates the health check names
Addresses [AB#81092](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81092).
Existing tests continue to pass.

Update healthcheck names.

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Common/DicomTagParserTests.cs
src/Microsoft.Health.Dicom.Core/Features/Common/DicomTagParser.cs

Fix bug: Invalid private  TagPath "Unknown" is accepted
Addresses [AB#80766](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80766)
All automation tests pass

Fix bug: Invalid private  TagPath "Unknown" is accepted

---

src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj

Update Microsoft.AspNetCore packages to fix CVE-2020-1045
N/A
Pass PR pipeline

Fix CVE-2020-1045

---

src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/ExtendedQueryTagEntryExtensionsTests.cs
src/Microsoft.Health.Dicom.Core/Extensions/ExtendedQueryTagEntryExtensions.cs

Fix bug 81015 - 500 error when adding a new instance
Addresses [AB#81015](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81015)
We should do null check when call vr.ToUppper()

Fix bug 81015 - 500 error when adding a new instance

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/GetExtendedQueryTagsServiceTests.cs
src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagsService.cs

[AB#81014](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81014)

Updating error message to contain tag name if supplied in get request.

---

README.md
docs/how-to-guides/extended-query-tags.md

Fix bug 81020: Doc improvements
Fix bug 81029: Sample from docs doesn't work
Addresses [AB#81020](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81020) , [AB#81029](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81029)

Improve extended query tag documentation

---

src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.ParameterParser.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/QueryTransactionTests.cs

Probably change in asp.net core on how the query param parsing is happening in IQueryCollection. We still need to RCA that.
For now I have added additional parsing of multiple values and an E2E test for OHIF viewer scenario
[AB#81876](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81876)
Added E2E test

Update multi-value includeField parser

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/DicomDatasetValidatorTests.cs

Fix build failure
Addresses [AB#81755](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81755)

Fix build failure

---

src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs

Add file size data to POST store information trace 
[82391](https://microsofthealth.visualstudio.com/Health/_workitems/edit/82391/)
No tests necessary

Add file size data to Store information trace

---

Microsoft.Health.Dicom.sln
src/Microsoft.Health.Dicom.Functions.UnitTests/Microsoft.Health.Dicom.Functions.UnitTests.csproj
src/Microsoft.Health.Dicom.Functions/Indexing/ReindexFunction.cs
src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj
src/Microsoft.Health.Dicom.Tests.Common/Microsoft.Health.Dicom.Tests.Common.csproj

- Initialize test project
- Fix packages
- Multi-target common test project
- Disable sample timer task
N/A
Build passes

Add Function Test Boilerplate

---

.github/workflows/CreateRelease.ps1

Remove skipping second week and release every week
[AB#82814](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82814)
Will monitor the release

Remove skipping second week and release every week

---

samples/templates/dicomcast-fhir-dicom-azuredeploy.json
samples/templates/dicomcast-quick-deploy.json

Fixes broken ARM template. The ARM template was broken due to changes in FHIR cosmos Db changes. 
Related Issue and PR in FHIR
https://github.com/microsoft/fhir-server/issues/1660
https://github.com/microsoft/fhir-server/pull/1700
Addresses [AB#82895](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82895)
Verified the ARM template validation was passed

Fix broken ARM template

---

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/OperationsControllerTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Operations/OperationStatusHandlerTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Operations/OperationsServiceTests.cs
src/Microsoft.Health.Dicom.Functions.Client.UnitTests/DicomAzureFunctionsHttpClientTests.cs
src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Serialization/OperationRuntimeStatusConverterTests.cs
src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Serialization/OperationTypeConverterTests.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Extensions/HttpRequestExtensionsTests.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Management/DurableClientProxyFunctionsTests.cs

- Rename new tests to conform with existing style
N/A
Pipelines passed

Rename Function Tests

---

release/scripts/PowerShell/DicomServerRelease/Private/Grant-ClientAppAdminConsent.ps1
release/scripts/PowerShell/DicomServerRelease/Public/Add-AadTestAuthEnvironment.ps1
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/AuthorizationTests.cs

Fix tenant admin consent url

---

docker/docker-compose.dependencies.yml
samples/docker/docker-compose.yaml

- Use 3.13 Azurite image tag for docker-compose projects
N/A
Ran VS project and sample locally

Update Azurite Image Tag

---

docs/development/code-organization.md

Fix typo in code-organization.md

---

Directory.Build.props
release/scripts/PowerShell/DicomServerRelease/Public/Add-AadTestAuthEnvironment.ps1
src/Microsoft.Health.Dicom.Blob/Features/Health/DicomBlobHealthCheck.cs
src/Microsoft.Health.Dicom.Metadata/Features/Health/MetadataHealthCheck.cs
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomServerBuilderSqlServerRegistrationExtensions.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/AuthorizationTests.cs

Reaction to this [PR](https://github.com/microsoft/healthcare-shared-components/pull/266/)
[AB#82460](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82460)
Local testing
Needs new nugets from shared after the reference PR is checked in

React to new Microsoft.Health.Blob changes to heathcheck APIs

---

src/Microsoft.Health.Dicom.Api/Controllers/ChangeFeedController.cs
src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs
src/Microsoft.Health.Dicom.Api/Controllers/QueryController.cs
src/Microsoft.Health.Dicom.Api/Controllers/RetrieveController.cs
src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs

Add produces and consumes attributes to the existing routes.
[AB#83343](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83343)

Fixes produces and consumes attributes in API Routes

---

docs/resources/conformance-statement.md
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryParserTests.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Features/Query/QueryLimit.cs
src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/AddInstanceTableValuedParametersBuilder.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/DicomTagSqlEntry.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/3.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/3.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/V2.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersion.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV3.cs
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomServerBuilderSqlServerRegistrationExtensions.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/QueryTransactionTests.cs

- Enable fuzzyMatch on ReferringPhysicianName 
- Add 2 more core tags PatientBirthDate ManufacturerModelName
[AB#80083](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80083)
Added new tests

Enable fuzzyMatch on ReferringPhysicianName 

---

build/ci-variables.yml
build/pr-variables.yml

Old service connection secret expired and could not reset the password.
[AB#83507](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83507)

Update pipelines to new azdevops service connection

---

src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs

small fix on GetTagAsync() logging.

Fix logging

---

release/scripts/PowerShell/DicomServerRelease/Private/Grant-ClientAppAdminConsent.ps1
release/scripts/PowerShell/DicomServerRelease/Public/Add-AadTestAuthEnvironment.ps1
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/AuthorizationTests.cs

Call GraphAPI to grant admin consent on Client Applications
Addresses [AB#83049](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83049)
All automated test passed.

Call GraphAPI to grant admin consent on Client Applications

---

tools/dicom-web-electron/index.html
tools/dicom-web-electron/window.js

Add the ability to specify version to the electron tool.
[AB#82674](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82674)
Manually tested to make sure storing and changefeed work.

Add versioning to the electron tool

---

docs/development/api-versioning-developers.md

Update developer docs for API versioning to include info about OpenApi/swagger doc diffs.
[AB#82660](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82660)
Read the docs :)

Update Developer Docs for Versioning

---

build/.vsts-ci.yml

Removes an Unused variable from the CI pipeline.

Remove Unused Variable From CI

---

docs/api-versioning.md
docs/development/setup.md
docs/how-to-guides/pull-changes-from-change-feed.md
docs/quickstarts/deploy-via-azure.md
docs/quickstarts/deploy-via-docker.md
docs/resources/Conformance-as-Postman.postman_collection.json
docs/resources/conformance-statement.md
docs/resources/faq.md
docs/resources/use-dicom-web-standard-apis-with-python.ipynb
docs/tutorials/use-dicom-web-standard-apis-with-c#.md
docs/tutorials/use-dicom-web-standard-apis-with-curl.md
docs/tutorials/use-dicom-web-standard-apis-with-python.md
docs/tutorials/use-the-medical-imaging-server-apis.md

Add REST API version to customer facing docs and update examples
[AB#82661](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82661)

Update docs with API version in url

---

Directory.Build.props

Fix `Authors` property

---

NOTICE.md

Updated as recommended by CELA for MS OSS repos
https://docs.opensource.microsoft.com/using/required-notice-template/
[AB#84188](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/84188)
Not needed

Notice for Microsft OSS repo updated

---

tools/dicom-web-electron/package-lock.json

Update Path Parse version in electron tool
[AB#84305](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/84305)

Update path parse version electron tool

---

docs/resources/use-dicom-web-standard-apis-with-python.ipynb
docs/tutorials/use-dicom-web-standard-apis-with-python.md

Fixes jupyter notebook and a broken link.
#932

Jupyter Notebook and Doc Update

---

src/Microsoft.Health.Dicom.Api/Configs/SwaggerConfiguration.cs

Updates the swagger configuration to allow for correctly setting the title.
Addresses [AB#83353](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83353).
Manually tested.

Update SwaggerConfiguration to correctly set Title

---

src/Microsoft.Health.Dicom.Core/Features/Indexing/IReindexDatasetValidator.cs
src/Microsoft.Health.Dicom.Core/Features/Indexing/InstanceReindexer.cs
src/Microsoft.Health.Dicom.Core/Features/Indexing/ReindexDatasetValidator.cs
src/Microsoft.Health.Dicom.Core/Features/Store/IIndexDataStore.cs
src/Microsoft.Health.Dicom.Core/Features/Store/LoggingIndexDataStore.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV1.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV4.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/InstanceStoreTests.cs

Reindex with Watermark instead of Uids
Addresses #AB84106
All automated tests pass

Reindex with Watermark instead of Uids

---

Directory.Build.props
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj

- Normalize packages versions
- Update `Microsoft.Health.Client` and in turn update indirect dependencies on `Microsoft.IdentityModel.*`
N/A
Run integration tests locally

Fix Integration Tests

---

Directory.Build.props
docker/docker-compose.dependencies.yml
samples/docker/docker-compose.yaml
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs
src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj
src/Microsoft.Health.Dicom.Blob/Registration/DicomServerBuilderBlobRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Metadata/Registration/DicomServerBuilderMetadataRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Web/appsettings.json
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DataStoreTestsFixture.cs

- Update blob service client registration for the following reasons:
1. Integrate blob client and underlying http request pipeline with existing DI service container
2. Reduce boilerplate
3. Streamline configuration whose types integrate with existing APIs
- Normalize JSON to 2 spaces for indent
- Bump version of Azurite image such that we can leverage latest blob client API
[AB#84923](https://microsofthealth.visualstudio.com/Health/_workitems/edit/84923)
PR pipeline and local unit test runs

Update Blob Service Client Registration APIs and Configuration

---

.github/workflows/test-docker.ps1
CredScanSuppressions.json
Microsoft.Health.Dicom.sln
docker/docker-compose.dcproj
docker/docker-compose.dependencies.yml
docker/docker-compose.vs.yml
docker/functions/Dockerfile
docker/functions/host_secrets.json
samples/docker/docker-compose.yaml
samples/templates/default-azuredeploy.json
src/Microsoft.Health.Dicom.Functions/Indexing/ReindexDurableFunction.Orchestration.cs

- Update docker-compose to successfully run DICOM operations
- Incorporate function authentication
- Centralize credential scan suppressions
- Remove race conditions in ARM template caused by azure function restarts
- Minor format fix
[AB#82320](https://microsofthealth.visualstudio.com/Health/_workitems/edit/82320)
Local testing

Enable docker-compose for Az Functions

---

src/Microsoft.Health.Dicom.Client/Models/OperationRuntimeStatus.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Extensions/OperationStatusExtensions.cs

- Fix out-of-sync enum values between service and client
N/A
PR pipeline

Fix OperationRuntimeStatus Enumeration in Client Lib

---

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/IndexDataStoreTests.cs

- Refactor test to be more resilient of parallel tests
N/A
Tested via local and PR pipeline runs

Fix Flaky Deletion Test Caused by Other Test Executions

---

src/Microsoft.Health.Dicom.Api.UnitTests/Extensions/HttpResponseExtensionsTests.cs
src/Microsoft.Health.Dicom.Api/Controllers/QueryController.cs
src/Microsoft.Health.Dicom.Api/Extensions/HttpResponseExtensions.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryParserTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryResponseBuilderTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryServiceTests.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Features/Query/Model/QueryExpression.cs
src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.cs
src/Microsoft.Health.Dicom.Core/Features/Query/QueryService.cs
src/Microsoft.Health.Dicom.Core/Messages/Query/QueryResourceResponse.cs
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Query/SqlQueryGeneratorTests.cs

Update QIDO to respect QueryStatus and header to include Erroneous attribute
Addresses [AB#84774](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/84774)
All tests pass

Update QIDO to respect QueryStatus and header to include Erroneous attribute

---

tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json

Fix security vulnerability by upgrade electron to use latest packages
Addresses [AB#85460](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85460)
Locally run and manually verified File Upload, Get feed.

Fix security vulnerability by upgrade electron to use latest packages

---

tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json

Update min version of ansi-regex
Addresses [AB#85460](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85460)
Manually tested main scenario

Update min version of ansi-regex

---

Directory.Build.props
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj

Update jwtbearer to 5.0.9
Addresses [AB#85404](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85404)
Tests continue to pass.

Update SdkPackageVersion to 5.0.9

---

src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj

Update Sql task version
[AB#85587](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85587)
Existing tests pass

Update Sql task version

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomTagsManager.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

Record instance/tag before store/add them
All automated tests pass

Record instance and tag before storing or adding them

---

tools/dicom-web-electron/index.html
tools/dicom-web-electron/window.js

The Pr adds the ability to upload files using electron app with data partition feature enabled.

Update electron app to support data partitions

---

Directory.Build.props

Bumping healthcare-shared-components to pull in test fix

---

Directory.Build.props
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs

This Pr updates to the latest healthcaresharedcomponent.
Addresses [issue #] (https://github.com/microsoft/healthcare-shared-components/pull/361)

Upgraded to latest healthcaresharedcomponent nuget

---

build/.vsts-ci.yml

Rename the stage name to match with PR pipeline to use the secret.

Rename the stage name to match with PR pipeline

---

test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj

- Do not warn on `NU5104`
N/A
- Packed all test projects locally!

Ignore Prerelease Package Warning for Integration Tests

---

.github/workflows/cleanup-azure-resources.yml
build/add-aad-test-environment.yml

Updated .github/workflows/cleanup-azure-resources.yml to include workflow env. variables to simplify PR/Deployment name formatters.
[AB#86411](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/86411)
Closed this PR and verified the workflow runs without any errors (Refer: [Successful PR close trigger action](https://github.com/microsoft/dicom-server/runs/4344034691?check_suite_focus=true))

[AB#86411] Updated Deployment Name format to cleanup resources

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

Add extended query tag as bvt test for paas
Addresses [AB#86986](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/86986)

Add extended query tag as bvt test for paas

---

docker/functions/Dockerfile
src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/ExtendedQueryTagControllerTests.cs
src/Microsoft.Health.Dicom.Api.UnitTests/Features/Filters/BodyModelStateValidatorAttributeTests.cs
src/Microsoft.Health.Dicom.Api/Features/Filters/BodyModelStateValidatorAttribute.cs
src/Microsoft.Health.Dicom.Api/Features/Swagger/ReflectionTypeFilter.cs
src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/ExtendedQueryTagEntryExtensionsTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/AddExtendedQueryTagEntryValidationTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/ExtendedQueryTagEntryValidatorTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Operations/OperationStatusHandlerTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/StrictStringEnumConverterFactoryTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/StrictStringEnumConverterTests.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/AddExtendedQueryTagEntry.cs
src/Microsoft.Health.Dicom.Core/Features/Indexing/IInstanceReindexer.cs
src/Microsoft.Health.Dicom.Core/Features/Indexing/InstanceReindexer.cs
src/Microsoft.Health.Dicom.Core/Features/Operations/OperationStatusHandler.cs
src/Microsoft.Health.Dicom.Core/Serialization/StrictStringEnumConverter.cs
src/Microsoft.Health.Dicom.Core/Serialization/StrictStringEnumConverterFactory.cs
src/Microsoft.Health.Dicom.Operations.UnitTests/Indexing/ReindexDurableFunctionTests.Activity.cs
src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV2.cs
src/Microsoft.Health.Dicom.Tests.Common/Extensions/DicomTagExtensions.cs
swagger/v1-prerelease/swagger.yaml
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ExtendedQueryTagStoreTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

- Ensure user has read access for fetching operation status
- Ignore DICOM instances that have been deleted between fetching the batch and performing the re-index
- Add non-root user to docker image for functions
- Update enum serialization to strictly use names
- Update swagger doc to include new APIs and use enum names instead of numbers
[AB#87003](https://microsofthealth.visualstudio.com/Health/_workitems/edit/87003)
Test pipelines

Misc Extended Query Tag Fixes

---

Directory.Build.props
docker/docker-compose.dependencies.yml
samples/docker/docker-compose.yaml
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Microsoft.Health.Dicom.SqlServer.UnitTests.csproj
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

- Update Healthcare Shared Components to 4.0.1
- Update `Microsoft.Data.SqlClient` to 4.0.0
- Disable XQT BVT until PAAS is ready
- Fix SQL connection strings for local connections
[AB#86627](https://microsofthealth.visualstudio.com/Health/_workitems/edit/86627/)
Build pipeline

Update Healthcare Shared Components

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableExceptionStore.cs

Change Dicom Cast logging for uids to match that of dicom service for log redaction.
[AB#87220](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87220)

cleanup dicom cast logging to match dicom service

---

src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj
src/Microsoft.Health.Dicom.Operations/Microsoft.Health.Dicom.Operations.csproj
tools/scale-testing/QidoFunctionApp/QidoFunctionApp.csproj
tools/scale-testing/StowFunctionApp/StowFunctionApp.csproj
tools/scale-testing/WadoFunctionApp/WadoFunctionApp.csproj
tools/scale-testing/WadoMetadataFunctionApp/WadoMetadataFunctionApp.csproj

Downgrade webjobs package after it could not be imported using upstream sources in ADO
N/A
Pipeline

Downgrade WebJobs Package

---

tools/dicom-web-electron/package-lock.json

- Run `npm update` for electron tool
N/A
Local testing

Run npm update for Electron Tool

---

src/Microsoft.Health.Dicom.Operations.Client/Registration/DicomServerBuilderFunctionClientRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Operations.Client/Serialization/MessageSerializerSettingsFactory.cs
src/Microsoft.Health.Dicom.Operations.UnitTests/Indexing/Models/BatchCreationArgumentsTests.cs
src/Microsoft.Health.Dicom.Operations.UnitTests/Indexing/ReindexDurableFunctionTests.Activity.cs
src/Microsoft.Health.Dicom.Operations.UnitTests/Indexing/ReindexDurableFunctionTests.Orchestration.cs
src/Microsoft.Health.Dicom.Operations.UnitTests/Serialization/MessageSerializerSettingsFactoryTests.cs
src/Microsoft.Health.Dicom.Operations/Indexing/Models/BatchCreationArguments.cs
src/Microsoft.Health.Dicom.Operations/Indexing/ReindexDurableFunction.Activity.cs
src/Microsoft.Health.Dicom.Operations/Registration/ServiceCollectionExtensions.cs
src/Microsoft.Health.Dicom.Operations/Serialization/MessageSerializerSettingsFactory.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

- Fix incorrect range check on max watermark for the `GetInstanceBatches*Async` activities
- Remove `$type` from durable function extension input/output representation
- Re-enable tests for PAAS to prevent future regressions
N/A
Pipeline

Fix Function Serialization and Input Validation

---

Directory.Build.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Microsoft.Health.DicomCast.Core.UnitTests.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Microsoft.Health.DicomCast.Core.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage.UnitTests/Microsoft.Health.DicomCast.TableStorage.UnitTests.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Microsoft.Health.DicomCast.TableStorage.csproj
src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj
src/Microsoft.Health.Dicom.Operations/Microsoft.Health.Dicom.Operations.csproj
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Microsoft.Health.Dicom.SqlServer.UnitTests.csproj
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj
tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json
tools/scale-testing/QidoFunctionApp/QidoFunctionApp.csproj
tools/scale-testing/StowFunctionApp/StowFunctionApp.csproj
tools/scale-testing/WadoFunctionApp/WadoFunctionApp.csproj
tools/scale-testing/WadoMetadataFunctionApp/WadoMetadataFunctionApp.csproj

- Update NuGet and npm packages
N/A
Pipeline and ad-hoc testing for electron

Update Packages Across Repository

---

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/AddWorkitemResponseBuilderTests.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/WorkitemServiceTests.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs
src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemDatasetValidator.Add.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemDatasetValidator.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemOrchestrator.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemResponseBuilder.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemService.Add.cs
src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStoreV9.cs
src/Microsoft.Health.Dicom.Tests.Common/Samples.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/WorkitemTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Add.cs

Validate Workitem UID
Addresses [issue #]. [AB#87263](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87263)
Added Unit Test coverage

Validate Workitem Instance UID

---

src/Microsoft.Health.Dicom.Api/Features/Filters/UpsRsFeatureFilterAttribute.cs
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj

Updating the feature configuration to be enabled if data partitions are enabled - see linked issue for discussion.
Addresses [AB#87272](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87272)
All tests pass.

Update feature behavior for UPS-RS

---

Directory.Build.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/ServiceCollectionExtensions.cs
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj
src/Microsoft.Health.Dicom.Api/Modules/MvcModule.cs
src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HttpIntegrationTestFixture.cs

This PR updates the healthcare shared components to version 4.0.23
Addresses [AB#88411](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88411).
Manual testing of DICOM cast using a local DICOM OSS instance.

Update healthcare shared components to 4.0.23

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/ExceptionStorage/IExceptionStore.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/ExceptionStorage/IntransientError.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/ExceptionStorage/RetryableError.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/Models/Entities/IntransientEntity.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableExceptionStore.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Registration/DicomCastTableRegistrationExtension.cs

This PR adds read APIs to the DICOM Cast Table Store provider.
Addresses [AB#87832](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87832).
Manually tested.

Add dicom cast read store APIs

---

src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobWorkitemStore.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/IIndexWorkitemStore.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/Model/WorkitemInstanceIdentifier.cs
src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemOrchestrator.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/11.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/11.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/V10.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersion.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Scripts/Sequences.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/AddWorkitemV11.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Workitem.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStoreV11.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStoreV9.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/WorkitemSqlQueryGenerator.cs
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/WorkitemTests.cs

Added Watermark in Workitem.
Updated Test fixtures and integration test to reflect the schema change.

Added Workitem Watermark

---

src/Microsoft.Health.Dicom.Api/Controllers/WorkitemController.Retrieve.cs
src/Microsoft.Health.Dicom.Core/Features/Audit/AuditEventSubType.cs

Fixed the audit mapping issue for retrieving of workitem.
Created a user story to add respective tests for workitem: https://microsofthealth.visualstudio.com/Health/_workitems/edit/88953
[AB#88912](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88912).

Fixed the audit mapping issue for retrieving of workitem.

---

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/ControllerMetadataTests.cs
src/Microsoft.Health.Dicom.Api/Controllers/ChangeFeedController.cs
src/Microsoft.Health.Dicom.Api/Controllers/DeleteController.cs
src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs
src/Microsoft.Health.Dicom.Api/Controllers/PartitionController.cs
src/Microsoft.Health.Dicom.Api/Controllers/QueryController.cs
src/Microsoft.Health.Dicom.Api/Controllers/RetrieveController.cs
src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs
src/Microsoft.Health.Dicom.Api/Controllers/WorkitemController.cs
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj

- Add unit tests for standard controller and action metadata
- Replace `Controller` with `ControllerBase` as our project does not include views
- Fix file structure in Visual Studio
Resolves [AB#88953](https://microsofthealth.visualstudio.com/Health/_workitems/edit/88953)
Tests pass

Add Tests for Controller Metadata

---

docs/concepts/worklist.md

Removes invisible `U+200b` characters from the doc file.
Docs change.

Removing invisible whitespace

---

converter/dicom-cast/build/docker/Dockerfile
docker/functions/Dockerfile

- Update .NET image
- Update functions image
N/A
Pipelines

Update Docker Images

---

src/Microsoft.Health.Dicom.Operations/Indexing/ReindexDurableFunction.Activity.cs

Log when reindex completes
Addresses [AB#89046](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/89046)

Log when reindex completes

---

src/Microsoft.Health.Dicom.Api/Controllers/QueryController.cs
src/Microsoft.Health.Dicom.Api/Controllers/WorkitemController.Query.cs

Remove logging query strings as they may contain PII data.
[AB#89241](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/89241)

Do not log Query Strings

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Add.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Query.cs

Add "bvt" test category to workitem tests to ensure we test end to end.

Add test category to workitem test

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Add.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Query.cs

Reverts microsoft/dicom-server#1388

Revert "Add test category to workitem test"

---

.github/workflows/combine-dependabot-prs.yml
NOTICE.md

Adds a workflow and license.
Will be manual

Adds a workflow to combine dependabot PRs

---

docs/resources/Conformance-as-Postman.postman_collection.json

Adds queries based on spec in https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/extended-query-tags.md
Addresses [AB#89395](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/89395)
Manual verification

Update postman with extended query tag requests

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

- Change tags so they don't overlap in BVTs
N/A
Pipelines pass

Use Different Tags in XQT E2E Tests to Minimize Concurrent Problems

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

Fix minor test code issues
Addresses [AB#88124](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88124)

Fix minor test code issues

---

docs/development/api-versioning-developers.md
docs/development/code-organization.md
docs/development/data-validation.md
docs/development/setup.md
docs/development/tests.md

Adds docs describing our approach to handling invalid data, some other updating / cleanup

Adding data validation dev docs

---

README.md
docs/resources/dicom-server-maintaince-guide.md
src/Microsoft.Health.Dicom.Api/Web/IHttpStreamContent.cs
src/Microsoft.Health.Dicom.Api/Web/LazyMultipartReadOnlyStream.cs

Update the manage service doc
[AB#90414](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/90414)
NA. Only doc and generalization of Lazy stream

Add more features to consider for managing the service.

---

build/.vsts-ci.yml
build/.vsts-pr.dotnet.yml

- Fix mapping of SemVer environment variables
N/A
Validate artifacts

Fix GitVersion Env Variables in PR and CI

---

build/ci/deploy.yml
samples/templates/default-azuredeploy.json

- Add resource group back to template for app service plan
N/A
ARM pipeline passes

Re-add App Service Plan Resource Group to Sample Template

---

build/.vsts-ci.yml
build/ci/run-e2e-features-enabled-tests.yml
build/ci/run-e2e-tests.yml

- Add `push` flag to CI
- Fix CI pipeline
N/A
Ensure CI runs : https://microsofthealthoss.visualstudio.com/DicomServer/_build/results?buildId=19299&view=results

Fix CI Pipeline and Enable Testing

---

Directory.Build.props
src/Microsoft.Health.Dicom.Functions.App/Microsoft.Health.Dicom.Functions.App.csproj
src/Microsoft.Health.Dicom.Functions.Client/Microsoft.Health.Dicom.Functions.Client.csproj
src/Microsoft.Health.Dicom.Functions.UnitTests/Microsoft.Health.Dicom.Functions.UnitTests.csproj
src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj

- Revert minimum version of durable task extension back to 6.2.1
N/A
Pipelines

Revert Minimum Version of DurableTask

---

docs/quickstarts/deploy-via-azure.md

- Fix button in quick start
N/A
Clicked it

Fix Deploy Button in Quick Start

---

release/templates/featuresenabled-azuredeploy.json
samples/templates/default-azuredeploy.json
src/Microsoft.Health.Dicom.Blob.UnitTests/DicomFileNameWithPrefixTests.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobMetadataStore.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobWorkitemStore.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/DicomFileNameWithPrefix.cs
src/Microsoft.Health.Dicom.Blob/Utilities/HashingHelper.cs
src/Microsoft.Health.Dicom.Web/appsettings.Development.json
src/Microsoft.Health.Dicom.Web/appsettings.json

Review comment fixes from previous PR !1159

Blob Migration review comment fixes

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Program.cs

Update KeyVault SDK used by DICOMcast
N/A
Pipelines

Update KeyVault SDK in DICOMcast

---

build/common/docker-build-push.yml
docker/functions/Dockerfile

Update docker step to build other containers for both component governance and public consumption.
- Push dicom-functions to our ACR
- Build SQL image
N/A
Build passes and CG picked up new dependencies

Build and push functions image

---

tools/dicom-web-electron/THIRDPARTYNOTICES.MD
tools/dicom-web-electron/main.js
tools/dicom-web-electron/package-lock.json
tools/dicom-web-electron/package.json

This PR replaces axios with node-fetch. There is currently an issue where axios is automatically replacing the content type `multipart/related` in the headers with `multipart/form-data`. This breaks our upload functionality.
Addresses [AB#91691](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/91691).
Manual testing.

Replace axios with node-fetch

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Microsoft.Health.DicomCast.Core.csproj
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/DicomModule.cs

Add retry handlers for dicomcast gets
[AB#91480](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/91480)

enable dicomcast to survive brief dicom outages AB#91480

---

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs

Fix versioning to allow _schema endpoint

Fix versioning to allow _schema endpoint

---

src/Microsoft.Health.Dicom.Web/wwwroot/index.html

This PR updates the OHIF viewer to be aware of our `v1` version.
Manually tested.

Update OHIF to support versioning

---

build/ci/run-e2e-features-enabled-tests.yml
build/ci/run-e2e-tests.yml
build/common/run-e2e-features-enabled-tests.yml
build/common/run-e2e-tests.yml
src/Microsoft.Health.Dicom.Tests.Common/Microsoft.Health.Dicom.Tests.Common.csproj
src/Microsoft.Health.Dicom.Tests.Common/TestEnvironment.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/AuthenticationSettings.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/InProcTestDicomWebServer.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/TestApplication.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/TestDicomWebServerFactory.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/TestUser.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj

- Update environment variable usage to be platform-agnostic, as variables are case-sensitive outside of Windows
- Migrate test pipeline stages to use Ubuntu
N/A
Successful CI

Migrate Tests to Ubuntu

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/Audit/AuditTests.Workitem.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/Audit/AuditTests.cs

Added Audit Tests for Workitem features (Add, Cancel, Retrieve and Query)
Addresses [[AB#88953](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88953)].
N/A

[AB#88953] Added Workitem Audit Tests

---

NOTICE.md
src/Microsoft.Health.Dicom.Api/Features/Partition/DataPartitionFeatureValidatorService.cs
src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj
src/Microsoft.Health.Dicom.Blob/Utilities/HashingHelper.cs

This PR includes changes related to 
1. Silently failing Data Partition feature validation service if the schema wasn't upgraded. 
2. Replace HashDepot with System.IO.Hashing
Addresses [AB#91991](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/91991).

Few fixes and improvements

---

converter/dicom-cast/Microsoft.Health.DicomCast.sln
tools/scale-testing/ScaleTesting.sln

- From `forks` folder from dicom-cast and tools solutions
N/A
N/A

Remove Forks Folder from Other Solutions

---

Directory.Packages.props
tools/dicom-auth-test/Microsoft.Health.Web.Dicom.Tool/Microsoft.Health.Web.Dicom.Tool.csproj
tools/dicom-auth-test/Microsoft.Health.Web.Dicom.Tool/Program.cs
tools/dicom-auth-test/Microsoft.Health.Web.Dicom.Tool/readme.md

Specified specified commandline dependency for the testing purpose.
Addresses [issue # 92834](https://microsofthealth.visualstudio.com/Health/_backlogs/backlog/Medical%20Imaging/Epics/?workitem=92834).
Ran it locally

Ignore  NU5104 warning for System.commandLine

---

tools/scale-testing/MessageHandler/MessageHandler.csproj
tools/scale-testing/MessageUploader/MessageUploader.csproj
tools/scale-testing/PersonInstanceGenerator/PersonInstanceGenerator.csproj
tools/scale-testing/QidoFunctionApp/QidoFunctionApp.csproj
tools/scale-testing/StowFunctionApp/StowFunctionApp.csproj
tools/scale-testing/WadoFunctionApp/WadoFunctionApp.csproj
tools/scale-testing/WadoMetadataFunctionApp/WadoMetadataFunctionApp.csproj

- Import latest version of Newtonsoft in projects that indirectly depend upon the package
N/A
Pipeline

Enforce Latest Newtonsoft.Json Packages

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/DicomModulesExtensions.cs

Changed return statement

---

tools/uploader-function/src/DicomUploaderFunction/DicomUploaderFunction.csproj
tools/uploader-function/src/DicomUploaderFunction/Startup.cs

- Update `Microsoft.AspNetCore.Http`
- Add `FrameworkReference` to normalize other dependencies
- Minor options refactor
N/A
Pipeline

Address CVE-2020-1045 in Uploader Function

---

Directory.Build.props

Update healthcare-shared-components version to pull in this change: https://github.com/microsoft/healthcare-shared-components/commit/20506ffba19905abe882812a25d74866d1e1dcb0
Addresses #93318.

update healthcare shared components version

---

docs/quickstarts/deploy-dicom-cast.md

fix deploy button image not loading

---

src/Microsoft.Health.Dicom.SqlServer/Features/Retrieve/SqlInstanceStoreV23.cs

Schema version was wrongly mentioned in previous PR. updating to correct one

Update to correct schema version

---

build/common/docker-build-push.yml

This PR updates the dicom-uploader docker push to also tag latest.

Update docker uploader push to tag latest also.

---

docs/resources/schema-manager.md
src/Microsoft.Health.Dicom.SchemaManager/Properties/Resources.Designer.cs
src/Microsoft.Health.Dicom.SchemaManager/Properties/Resources.resx

This PR adds a new markdown file with documentation for the new DICOM Schema Manager.

Create documentation for DICOM Schema Manager

---

src/Microsoft.Health.Dicom.SchemaManager/README.md

This PR adds documentation on how to test DICOM Schema Manager locally.

Add documentation for testing DICOM Schema Manager.

---

Directory.Build.props
Directory.Packages.props

Adds prop for token packages that share a version.

Adding prop for token packages

---

build/ci/variables.yml
build/common/docker-build-push.yml
build/pr/run-e2e-features-enabled-tests.yml
build/pr/run-e2e-tests.yml
build/pr/variables.yml
docker/docker-compose.yml
docker/functions/Dockerfile
src/Microsoft.Health.Dicom.Blob.UnitTests/Features/Export/AzureBlobExportSinkProviderTests.cs
src/Microsoft.Health.Dicom.Blob/Extensions/AzureBlobExportOptionsExtensions.cs
src/Microsoft.Health.Dicom.Blob/Features/Export/AzureBlobExportSinkProvider.cs
src/Microsoft.Health.Dicom.Core/Features/Common/DefaultExternalOperationCredentialProvider.cs
src/Microsoft.Health.Dicom.Core/Features/Common/IExternalOperationCredentialProvider.cs
src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs
src/Microsoft.Health.Dicom.Functions.App/local.settings.json
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExportTests.cs

- Enable Export E2E Test in PaaS
- Minor refactor to remove unnecessary async behavior
- Refactor some docker usage
N/A
Existing tests

Enable Export E2E Test

---

src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs

Add changefeed store to SQL functions registration. To be used by events function
Addresses #94386

Add changefeed to sql functions registration

---

docs/resources/conformance-statement.md

Updates the conformance statement with how we handle Dicom file preambles, addressing the known vulnerability.

Updating conformance statement regarding preamble vulnerability

---

Directory.Build.props

- Update shared components
N/A
N/A

Update Shared Components to Latest

---

Directory.Build.props

Update the  healthcareshared component version
Addresses [#95629](https://microsofthealth.visualstudio.com/Health/_workitems/edit/95629).

Update shared component version

---

docs/resources/conformance-statement.md

Updates minor issues in the conformance statement, including making sure standard response codes are listed for each transaction.

Cleaning up conformance statement

---

.globalconfig
src/Microsoft.Health.Dicom.Api/Features/Telemetry/DicomTelemetry.cs
src/Microsoft.Health.Dicom.Api/Features/Telemetry/DicomTelemetryInitializer.cs
src/Microsoft.Health.Dicom.Api/Features/Telemetry/HttpDicomTelemetryClient.cs
src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs
src/Microsoft.Health.Dicom.Core/Extensions/IDicomTelemetryClientExtensions.cs
src/Microsoft.Health.Dicom.Core/Features/Store/StoreService.cs

Fix aggregation of instance bytes when storing instances
N/A
Validated via app insights

Fix Min Instance Byte Metric

---

tools/dicom-web-electron/window.js

This PR updates the rendering of input elements as HTML.
Manually tested.

Update Electron DOM rendering

---

Directory.Build.props
Directory.Packages.props
src/Microsoft.Health.Dicom.Benchmark/Microsoft.Health.Dicom.Benchmark.csproj
src/Microsoft.Health.Dicom.Blob.UnitTests/Features/Export/AzureBlobExportSinkTests.cs
src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj
src/Microsoft.Health.Dicom.SchemaManager.UnitTests/Microsoft.Health.Dicom.SchemaManager.UnitTests.csproj
src/Microsoft.Health.Dicom.SchemaManager/Microsoft.Health.Dicom.SchemaManager.csproj
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Microsoft.Health.Dicom.SqlServer.UnitTests.csproj
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj

Downgrade blob version
see - https://github.com/Azure/azure-sdk-for-net/issues/31940

downgrade azure blob

---

Directory.Packages.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj

Fix pipelines by using later version of drawing

use later version of drawing

---

.github/dependabot.yml

Ensure that all sub projects get dependabot updates

add dependabot for other .sln

---

src/Microsoft.Health.Dicom.Api/Web/SeekableStreamConverter.cs

https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/FileBufferingReadStream.cs
FileBufferingReadStream uses memory buffer of shared byte array pool if memoryThreshold is <= 1MB. Otherwise it is using MemoryStream which is not efficient memory reuse.
// New logic works like below
// If dcm file is > 1MB, drain it to file and return filestream since memoryBufferThreshold is set to 0
// else use the memory buffer of <= 1MB created with bytePool.Rent(memoryThreshold) to create the seekable stream
[AB#98172](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/98172)
Existing functional tests pass

Improve memory and cpu usage of POST call

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj

Fix running e2e tests locally
Tests were run locally.

Fix running e2e tests locally

---

forks/Microsoft.Health.FellowOakDicom/Core/DicomElement.cs

Sync'ing JsonDicomConverter and related changes from fo-dicom to the fork in dicom-server
Addresses [[AB#93875](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93875)].
Unit tests

Changes from fo-dicom PR

---

docker/functions/Dockerfile

Update image to more frequently updated tag
N/A
Pipeline

Update Azure Function Base Image

---

Directory.Build.props
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DataStoreTestsFixture.cs

- Update shared components with new health check logic for blob storage
N/A
Pipelines

Update Shared Components

---

README.md

Update Readme.md for blob storage migration

---

docker/functions/Dockerfile

Update to latest to fix component governance alert - https://microsofthealthoss.visualstudio.com/DicomServer/_componentGovernance/166566/alert/8178432?typeId=6296245&pipelinesTrackingFilter=0
Got the latest from: https://mcr.microsoft.com/en-us/product/azure-functions/dotnet/tags

Update azure functions image 

---

docs/resources/conformance-statement.md
src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Query/SqlQueryGeneratorTests.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryGenerator.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/28.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/28.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/V27.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersion.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/AddInstanceV6.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ChangeFeed.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/DeletedInstance.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTag.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTagDateTime.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTagDouble.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTagLong.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTagPersonName.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/ExtendedQueryTagString.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Instance.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Series.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Study.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Workitem.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Views/SeriesResultView.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Views/StudyResultView.sql
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.SqlServer/indexes.md
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Series.cs

Details of the context in the PR md file.
Basically, include  paritionKey consistently on all indexes, except some exception cases
[AB#98125](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/98125)
Local testing
planning to skip compat perf for now

Fix indexes in core tables

---

docs/resources/conformance-statement.md

Updated conformance statement matching DICOM spec - IE Levels specified in [Table 10.6.1-4.](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#table_10.6.1-4)
Addresses [issue [AB#99817](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/99817)].

Update conformance statement to match DICOM spec

---

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/28.diff.sql

Fix migration script for Series table

Fix migration script for Series table

---

tools/uploader-function/src/DicomUploaderFunction/DicomUploaderFunction.csproj

Update Azure.Storage.Queues indirect dependency in uploader tool
CVE-2022-30187
PR pipeline

Update Azure.Storage.Queues Dependecy in Uploader Tool

---

.github/CODEOWNERS
docs/resources/v2-conformance-statement.md

Create a new V2 conformance statement
[AB#98125](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/98125)
NA

doc changes for QIDO v2 in conformance

---

.github/CODEOWNERS

This requires approval from Matt on Markdown files only.

updating code owner

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Program.cs

DicomCast was failing at startup due to missing DicomCastMeter and AppInsights configuration inside service container. 
Addresses [issue [100846](https://microsofthealth.visualstudio.com/DefaultCollection/Health/_workitems/edit/100846)].
Ran tests manually and verified the startup

Fix startup issue

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Dockerfile
src/Microsoft.Health.Dicom.Functions.App/Docker/Dockerfile
src/Microsoft.Health.Dicom.Web/Dockerfile
tools/uploader-function/src/DicomUploaderFunction/Dockerfile

Updating dotnet sdk and runtime images

---

src/Microsoft.Health.Dicom.Api/Logging/TelemetryInitializer.cs
src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs

Extend ITelemetryInitializer to add a new custom column
[AB#100795](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/100795)
Existing tests pass

Add APIVersion column to telemetry

---

src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryStoreV27.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/QueryStoreTests.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs

Make the column value nullable type when converting
[AB#100958](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/100958)
Added new integration test

Fix bug when GetStudyResult fails when Modality is null

---

Directory.Build.props
Directory.Packages.props

Reverts microsoft/dicom-server#2442
https://github.com/Azure/azure-sdk-for-net/issues/34784
https://github.com/Azure/azure-sdk-for-net/pull/34800

Revert "Bump Azure.Core from 1.28.0 to 1.29.0

---

Directory.Build.props
Directory.Packages.props

Upgrade Azure.Core and shared component package version to fix https://github.com/Azure/azure-sdk-for-net/issues/34784

Upgrade Azure.Core and shared component package version

---

Directory.Packages.props

Updated fo-dicom.Codecs package to 5.10.2
Addresses issue# 101771.
Tested /instance and /frames apis using a few test dcm files

Updated fo-dicom.Codecs package

---

Directory.Build.props
Directory.Packages.props

Updated package from healthcare shared components related to sql authentication
Addresses [UserStory #102136](https://microsofthealth.visualstudio.com/Health/_workitems/edit/102136).
Manually tested end to end.

Updated package from healthcare shared components related to sql authentication

---

src/Microsoft.Health.Dicom.Blob.UnitTests/DicomFileNameWithPrefixTests.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobMetadataStore.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/DicomFileNameWithPrefix.cs
src/Microsoft.Health.Dicom.Blob/Features/Storage/IDicomFileNameBuilder.cs

Introduce fall back logic for frame range blob client and fix existing space issue
Addresses [[AB#102654](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/102654)].
Unit test added

Introduce fall back logic for frame range blob client

---

build/ci/deploy-features-enabled-webapp.yml
build/ci/deploy.yml

Run of pipeline can be found here: https://microsofthealthoss.visualstudio.com/DicomServer/_build/results?buildId=30369&view=results

Update CI deployment to use ZipDeploy

---

Microsoft.Health.Dicom.sln
src/Microsoft.Health.Dicom.Api.UnitTests/Web/AspNetCoreMultipartReaderTests.cs
src/Microsoft.Health.Dicom.Api.UnitTests/Web/HttpSeekableStreamConverterTests.cs
src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj
src/Microsoft.Health.Dicom.Api/Modules/WebModule.cs
src/Microsoft.Health.Dicom.Api/Web/HttpSeekableStreamConverter.cs
src/Microsoft.Health.Dicom.WebUtilities/Microsoft.Health.Dicom.WebUtilities.csproj
src/Microsoft.Health.Dicom.WebUtilities/SeekableStreamConverter.cs

Addresses [AB#96436](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/96436).

Abstract the SeekableStreamConverter

---

docs/resources/Conformance-as-Postman.postman_collection.json
docs/resources/conformance-statement.md

Update conformance statement and postman collection for render.
Addresses [[AB#100779](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/100779), [AB#101537](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/101537)].

Update conformance statement and postman collection for render

---

build/common/versioning.yml

Enable swagger verification

---

src/Microsoft.Health.Dicom.Web/appsettings.json

Update feature flag name in appsettings.json. This was merged wrongly in previous PR

Update feature flag name in appsettings.json

---

src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobMetadataStore.cs

Add log to ensure fallback logic is used.

Add log to ensure fallback logic is used.

---

src/Microsoft.Health.Dicom.Core.UnitTests/AutoValidationCollection.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreDatasetValidatorTestsV1.cs
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreDatasetValidatorTestsV2.cs
test/Microsoft.Health.Dicom.Tests.Integration/ChangeFeedCollection.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ChangeFeedTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/ChangeFeedCollection.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ChangeFeedTests.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/TemporalChangeFeedTests.cs

Our test collections are used improperly according to the docs: https://xunit.net/docs/shared-context
Related docs: https://xunit.net/docs/running-tests-in-parallel
Thanks @esmadau for finding issues with our tests.
N/A
PR Pipeline

Use Proper XUnit Test Collection Syntax

---

docs/resources/v2-conformance-statement.md

Add rendered to v2 of conformance statement

update v2 of conformance for rendered

---

src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Activity.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Orchestration.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Activity.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs

A new cleanup function to remove the newly added blob in case of a failure.
Addresses [[issue #102010](https://microsofthealth.visualstudio.com/Health/_workitems/edit/102010)].
Manual testing

Dicom update cleanup function

---

docs/concepts/bulk-update.md
docs/concepts/change-feed.md
docs/resources/Conformance-as-Postman.postman_collection.json
docs/resources/v2-conformance-statement.md

Bulk update conformance statement doc
Addresses [[AB#102073](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/102073)].

Bulk update conformance statement doc

---

src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs
src/Microsoft.Health.Dicom.Core/Features/Model/InstanceFileIdentifier.cs
src/Microsoft.Health.Dicom.Core/Features/Model/InstanceProperties.cs
src/Microsoft.Health.Dicom.Functions.Abstractions/Update/UpdateCheckpoint.cs
src/Microsoft.Health.Dicom.Functions.Abstractions/Update/UpdateResult.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs

Add additional telemetry for update operation and few comments
Addresses [[AB#102014](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/102014)].

Add additional telemetry for update operation and few comments

---

Directory.Packages.props

Upgrade fodicom nuget package
Addresses [issue #104627](https://microsofthealth.visualstudio.com/Health/_workitems/edit/104627).

Upgrade fodicom package

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/DicomModulesExtensions.cs

DICOMcast queries the entire Change Feed and maintains an offset. This pattern is better done against the original V1 implementation of our DICOM service's Change Feed API.
N/A
Test pipeline

Pin DICOMcast to V1 API

---

build/ci/deploy.yml
build/ci/variables.yml

Update CI variables for new connection principal

Update CI variables for new connection principal

---

Directory.Packages.props

Update health care shared component nugets
Addresses [issue #105436](https://microsofthealth.visualstudio.com/Health/_workitems/edit/105436)

Updated health care shared components nuget

---

renovate.json

Disable package updates for packages related to FHIR
N/A
N/A

Prevent FHIR Dependabot Updates

---

converter/dicom-cast/samples/templates/default-azuredeploy.json
converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json
samples/templates/dicomcast-fhir-dicom-azuredeploy.json
samples/templates/dicomcast-quick-deploy.json

dicom-cast image does not have "latest", you need to specify a specific tag
Addresses [105719].

specify tag for dicom cast images

---

tools/dicom-web-electron/index.html

Add support for v2 api and remove v1-prerelease

Electron tool - Add v2 support and remove pre-release

---

build/ci/run-e2e-tests.yml
build/common/run-e2e-tests.yml
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/44.sql
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

External store tests do not actually test its functionality for the remote CI tests, so this PR disables these extraneous tests.
Also, updates code-gen format and remove warning suppressions.
N/A
N/A

Remove External Store Tests for CI

---

Directory.Packages.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj
src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj

remove "Microsoft.IdentityModel.Clients.ActiveDirectory"

remove identity model

---

build/ci/run-e2e-tests.yml
build/common/run-e2e-tests.yml
src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs
src/Microsoft.Health.Dicom.Core/Features/Common/IFileStore.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Activity.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Orchestration.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Activity.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Move original version to cold storage after successful update
Addresses [[AB#103334](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/103334)].
Added new unit tests

Move original version to cold storage after successful update

---

src/Microsoft.Health.Dicom.Client/DicomWebClient.Retrieve.cs

This will help for the caller to dispose stream easily than DicomFile which does not give access to Dispose

Add RetrieveInstance that returns a Stream instead of DICOMFile

---

Directory.Packages.props
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Fhir/FhirTransactionExecutorTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Fhir/FhirTransactionExecutor.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/DicomCastWorker.cs

- Update FHIR Client to remove dependency on legacy app authentication library
N/A
Unit tests

Update FHIR Client to Fix Component Governance

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Fix test to use multi-part STOW for SOP instances from different studies
N/A
Pass tests

Fix Test by Using Proper STOW API

---

Directory.Packages.props

Upgrade HSS to downgrade IdentityModel.* to 6.* from 7.*

Upgrade HSS to downgrade IdentityModel.* to 6.* from 7.*

---

renovate.json

Update renovate.json to skip IdentityMode 7.x

Update renovate.json to skip IdentityMode 7.x

---

src/Microsoft.Health.Dicom.SchemaManager.Console/Program.cs
src/Microsoft.Health.Dicom.SchemaManager/CommandCollectionExtensions.cs
src/Microsoft.Health.Dicom.SchemaManager/CommandLineOptions.cs
src/Microsoft.Health.Dicom.SchemaManager/OptionAliases.cs
src/Microsoft.Health.Dicom.SchemaManager/SchemaManagerServiceCollectionBuilder.cs

Add new option to enable workload identity support
[AB#111048](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111048/)
Test in PaaS

Add Support for Workload Identity to Schema Manager

---

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/FileStoreTests.cs

Added test to verify cold tier

Added test to verify cold tier - This cannot be merged until new Azurite release

---

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs

Update max version to 49
N/A
N/A

Update Max SQL Version

---

build/ci/run-e2e-tests.yml
build/common/run-e2e-tests.yml

Azurite has released new version and now supports changing access tier.
Enable update tests on PR builds

Enable update tests on PR builds

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomTagsManager.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs

Do not throw when cleaning up tags for test
N/A
N/A

Do Not Throw During Test Clean Up

---

converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json

Update dicom cast image format and api versions in dicom cast deployment template
Addresses [issue #3142](https://github.com/microsoft/dicom-server/issues/3142), [issue #111273](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111273).
Manual testing

Update image format and api versions in dicom cast template

---

build/ci/deploy.yml
docker/docker-compose.yml
docs/concepts/bulk-update.md
src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs
src/Microsoft.Health.Dicom.Core/Configs/FeatureConfiguration.cs
src/Microsoft.Health.Dicom.Web/appsettings.json
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/InProcTestDicomWebServer.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Remove EnableUpdate feature flag.
Addresses [[AB#111343](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/111343)].

Remove EnableUpdate feature flag

---

converter/dicom-cast/docs/DicomcastDeploymentTemplate.md

Fix the default image for dicom cast

Fix the default image for dicom cast

---

build/common/docker-build-push.yml

Update docker-build-push.yml to push latest for dicom-cast

Update docker-build-push.yml to push latest for dicom-cast

---

build/common/docker-build-push.yml

Push latest dicom-cast build

---

src/Microsoft.Health.Dicom.Core/Features/Store/IIndexDataStore.cs
src/Microsoft.Health.Dicom.Functions.App/host.json
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Activity.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Orchestration.cs
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.cs
src/Microsoft.Health.Dicom.Functions/Update/Models/UpdateInstanceBlobArgumentsV2.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Activity.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/50.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/50.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/V49.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersion.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/EndUpdateInstanceV50.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStore.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV1.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV37.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV49.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV50.cs
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Web/appsettings.json
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ChangeFeedTests.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/InstanceStoreTests.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Today while doing DICOM update, extended query tags are update for a particular study. This PR address that issue and make sure the extended query tag is updated.
SQL execution plan for new SQL changes
Addresses [AB#112033].
Updated tests and added new E2E test to verify

Index ExtendedqueryTag on dicom update for a study

---

docs/concepts/bulk-update.md
src/Microsoft.Health.Dicom.Core.UnitTests/Features/Update/UpdateRequestValidatorTests.cs
src/Microsoft.Health.Dicom.Core/Features/Update/UpdateTags.cs

Add Issuer of PatiendID to list of study tags
Addresses [AB#112517].

Add Issuer of PatiendID to list of study tags

---

docs/concepts/bulk-update.md
src/Microsoft.Health.Dicom.Core/Features/Update/UpdateTags.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/52.diff.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/52.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/V51.Generated.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersion.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/EndUpdateInstanceV52.sql
src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV52.cs
src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj
src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/InstanceStoreTests.cs
test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Add more study tags for DICOM update.
**General study module**
| Attribute Name   | Tag           | Description           |
| ---------------- | --------------| --------------------- |
| Referring Physician's Name | (0008,0090)   | Name of the Patient's referring physician   |
| Accession Number | (0008,0050)   | A RIS generated number that identifies the order for the Study. |
| Study Description | (0008,1030) | Institution-generated description or classification of the Study (component) performed. 
Addresses AB#112517
Added integration and E2E tests

Add more study tags for DICOM update

---

src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveHelpers.cs
src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveRenderedService.cs
src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs

Log file size for NotAcceptableException to determine the size of the DICOM file

Log file size for NotAcceptableException

---

src/Microsoft.Health.Dicom.Client/Models/UpdateResults.cs
src/Microsoft.Health.Dicom.Client/Serialization/OperationStateConverter.cs
src/Microsoft.Health.Dicom.Functions.Abstractions.UnitTests/Update/UpdateCheckpointTests.cs
src/Microsoft.Health.Dicom.Functions.Abstractions/Update/UpdateCheckpoint.cs
src/Microsoft.Health.Dicom.Functions.Abstractions/Update/UpdateResult.cs
src/Microsoft.Health.Dicom.Functions.App/host.json
src/Microsoft.Health.Dicom.Functions.UnitTests/Update/UpdateDurableFunctionTests.Orchestration.cs
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs
src/Microsoft.Health.Dicom.Web/appsettings.json
test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Populate update results correctly and fix web client which wasn't returning UpdateResult.
Addresses AB#113561
New tests added to validate update results.

Populate update results correctly

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Dockerfile
src/Microsoft.Health.Dicom.Web/Dockerfile

Reverts microsoft/dicom-server#3276

Revert "Update mcr.microsoft.com/dotnet/aspnet:8.0.0-alpine3.18-amd64 Docker digest to f8163ae"

---

Directory.Build.props
Directory.Packages.props
renovate.json
src/Microsoft.Health.Dicom.WebUtilities/Microsoft.Health.Dicom.WebUtilities.csproj

Reverts microsoft/dicom-server#3278

Revert "Update Pkgs for .NET 8"

---

src/Microsoft.Health.Dicom.Api/Modules/SecurityModule.cs

Reverts microsoft/dicom-server#3281

Revert "Set DefaultMapInboundClaims to false to keep roles claim type"

---

docs/concepts/bulk-update.md
src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs
src/Microsoft.Health.Dicom.Api/Features/Conventions/ApiVersionsConvention.cs
swagger/v1-prerelease/swagger.yaml
swagger/v1/swagger.yaml
swagger/v2/swagger.yaml
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Use update study only for v2
Addresses [AB#113876].
Add new tests to validate it works only in v2

Use update study only for v2

---

src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs
test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Fix update processing in durable function
Addresses AB#114006

Fix update processing in durable function

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs

Add update tests to verify pixel data on GET instance

Add update tests to verify pixel data on GET instance

---

docs/concepts/bulk-update.md
src/Microsoft.Health.Dicom.Functions/Update/UpdateDurableFunction.Orchestration.cs

Include information about changes in DICOM file meta information
Addresses [AB#113562].

Bulk update doc updates

---

GeoPol.xml

Update GeoPol.xml to exclude wwwroot folder

---

src/Microsoft.Health.Dicom.Functions.Client/Registration/DicomServerBuilderFunctionClientRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Web/Startup.cs

Disable durable task health check if running locally
Issue AB#114747

Local Environment: Disable Durable Task Health Check 

---

src/Microsoft.Health.Dicom.Blob.UnitTests/Features/Health/DicomConnectedStoreHealthCheckTests.cs
src/Microsoft.Health.Dicom.Blob/Extensions/BlobStorageErrorExtensions.cs
src/Microsoft.Health.Dicom.Blob/Registration/DicomServerBuilderBlobRegistrationExtensions.cs
src/Microsoft.Health.Dicom.Core/Configs/FeatureConfiguration.cs
src/Microsoft.Health.Dicom.Web/appsettings.json

Add new error when HNS is not enabled as a customer error
Addresses #114879
Unit tests

add new error as customer error; add option to disable health check

---

src/Microsoft.Health.Dicom.Blob/Utilities/ExternalBlobDataStoreConfiguration.cs

Add default value for health check expiry
Addresses #114888
N/A

Add default value for health check expiry

---

src/Microsoft.Health.Dicom.Blob/Utilities/ExternalBlobDataStoreConfiguration.cs

EnsureArg checks for null in the http pipeline policy
Addresses #114888
N/A

Add default for health file path

---

build/pr/run-e2e-features-enabled-tests.yml
build/pr/run-e2e-tests.yml

Ensure that logs exist in compose log files
Addresses [issue AB#114894].

add compose timestamps

---

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/Observation/ObservationParserTests.cs
converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/Observation/ObservationParser.cs

Ignore dicom cast validation bug when adding irradiation events and dose summary reports
Addresses [AB#114198].
Tested locally

Dicom Cast Validation Bug

---

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/AuthorizationTests.cs

Skip readonly authorization test

---

.github/workflows/codeql-analysis.yml
README.md

- Fix permissions for CodeQL
- Remove ADO Pipeline from README

Fix CodeQL Pipeline

---

.github/workflows/codeql-analysis.yml

Remove javascript from the codeql language
[AB#134139](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/134139)

Remove javascript from the codeql language

---

.github/workflows/codeql-analysis.yml

Add JavaScript to CodeQL workflow

Add JavaScript to CodeQL workflow
