microsoft/dicom-server

docs/resources/Conformance-as-Postman.postman_collection.json, docs/resources/use-dicom-web-standard-apis-with-python.ipynb, docs/tutorials/use-dicom-web-standard-apis-with-curl.md, docs/tutorials/use-dicom-web-standard-apis-with-python.md
Add necessary documentation to Python, cURL and Postman walkthroughs to highlight the newly added (non-DICOMweb standard) API to upload a single file without needing to use multipart/related
Addresses #349 
On a new install of the Medical Imaging Server for DICOM, I ran through cURL, Postman and Python end-to-end
=> Add Python, cURL and Postman documentation for single file upload

docs/resources/use-dicom-web-standard-apis-with-python.ipynb, docs/tutorials/use-dicom-web-standard-apis-with-python.md
Update python docs to show reading multipart/related responses. That's been difficult for some users. Putting an example in the docs is a good way to solve it.
Addresses [AB#76229](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76229)
Tested by running in Jupyter notebook against latest Medical Imaging Server for DICOM instance.
=> Update python docs to show reading multipart/related responses

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveResourceServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveTransferSyntaxHandlerTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Messages/Retrieve/AcceptHeaderTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveTransferSyntaxHandler.cs, src/Microsoft.Health.Dicom.Core/Messages/Retrieve/AcceptHeader.cs, test/Microsoft.Health.Dicom.Tests.Integration/Features/RetrieveResourceServiceTests.cs
There are a lot of reason retrieving resources could return NotAcceptable, log accept headers for diagnosis convenience.
Getting transfer syntax for retrieving 'Frames' with accept headers 'MediaType:'application/octet-stream', PayloadType:'MultipartRelated', TransferSyntax:'', Quality:'''.
Addresses https://microsofthealth.visualstudio.com/Health/_workitems/edit/75185
=> Log AcceptHeaders for retrieving resources

tools/dicom-web-electron/readme.md
I didn't know where to find sample DICOM files when going through walkthroughs for electron readme. Added a link to address that issue.
Clicked comment link in branch and took me to dicom samples folder.
=> add link for dcm files in electron readme

.gitignore
Was using .env files for docker-compose setup, want to ignore them from environment.
N/A
=> ignore .env file for docker compose

build/docker/sql/Dockerfile, samples/docker/docker-compose.yaml
Do not expose azure emulator and sql ports to host. This will prevent them from colliding if sql server or azure storage emulator is installed in the host already
Did the following simultaneously 
* Started azure storage emulator and sql server on machine 
* ran dicom tests
* started docker-compose environment
* uploaded dicom files to docker-compose environment
=> Dont fwd azure emulator & sql to host in compose

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs
Async and sync versions are missing resulting in threads deadlocking.
This fix replaces sync Start() with async InitializeAsync()
=> Fix integration tests timing out on schema initialization

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs
Prevent processing of change feed entry if the action is Create but the state is Deleted.
https://microsofthealth.visualstudio.com/Health/_workitems/edit/76453
=> Fix Bug: Dicom Cast error when processing changefeed entry that has been deleted

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Fhir/FhirTransactionExecutorTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/FhirResourceBuilder.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyDeleteHandlerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyUpsertHandlerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/FhirTransactionRequestMode.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyDeleteHandler.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelper.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyUpsertHandler.cs
Delete empty resource from FHIR when ImagingStudy that was created by Dicom-Cast no longer has any instances in it.
https://microsofthealth.visualstudio.com/Health/_workitems/edit/76454
Unit tests added and tested locally running local instances of dicom-cast, dicom-server, and fhir.
=> Dicom-Cast Delete

src/Microsoft.Health.Dicom.Api/Web/AspNetCoreMultipartReader.cs, src/Microsoft.Health.Dicom.Core/Exceptions/InvalidMultipartRequestException.cs
Invalid multipart request was throwing an internal server error when missing new line. Updated to throw 400 Bad Request error.
https://microsofthealth.visualstudio.com/Health/_workitems/edit/73702
Reproduced original bug and validated 400 Bad request thrown instead of 500 internal server error.
=> Bug Fix: Invalid Multipart Request Causes Internal Server Error

.github/workflows/cleanup-azure-resources.yml
add a workflow to clean up azure resources when PR is closed
https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=76751
Verified on private [repository](https://github.com/pengchen0692/TestRepository/blob/penche/somechange/.github/workflows/cleanup_azure_resources.yml):
* When PR is merged to master, the action is triggered and able to query with PR number
* When PR is manually closed, the action is triggered and able to query with PR number
=> Clean up azure resources when PR is closed

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/FhirTransactionContextBuilder.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyDeleteHandlerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelperTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPropertySynchronizerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyUpsertHandlerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/ValidationUtility.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/FhirTransactionConstants.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPipelineHelper.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/ImagingStudy/ImagingStudyPropertySynchronizer.cs
Add Accession Number to Fhir ImagingStudy
Addresses https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=76989
* Added unit tests, and all unit tests pass
* When study has accession number, it is synced to FHIR
```  
"identifier": 
[
{
"system": "urn:dicom:uid",
"value": "urn:oid:2.25.306734014169222155358388162298278737129"
},
{
"type": 
{
"coding": 
[
{
"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
"code": "ACSN"
}
]
},
"value": "0123456"
}
],
```
* When study doesn't has accession number
```
"identifier": 
[
{
"system": "urn:dicom:uid",
"value": "urn:oid:1.2.276.0.75.2.1.11.1.1.200709113729721.966169828020.1000004"
}
],
```
=> Add accession number when sync to FHIR

src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj
Adds a direct reference to Microsoft.AspNetCore.Http to mitigate CVE-2020-1045.
Addresses [AB#77157](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/77157).
Tests continue to run
=> Direct reference to Microsoft.AspNetCore.Http

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/DicomCastWorkerTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/DicomCastWorker.cs
Log unhandled exception in DicomCastWorker.ExecuteAsync, and exit application
When retrieve change feed fails for authentication, we don't log anything. This change logs that exception, and quit application
Addresses https://microsofthealth.visualstudio.com/Health/_workitems/edit/76891
Any exception in ExecuteAsync should be caught, since it won't be able to raise up to upper level (like Main method).
For more details, please refer to:
* [Exceptions in BackgroundService ExecuteAsync are (sometimes) hidden](https://github.com/dotnet/extensions/issues/2363)
* [Exception thrown from task is swallowed if thrown after 'await']( https://stackoverflow.com/questions/56871146/exception-thrown-from-task-is-swallowed-if-thrown-after-await )
Verified locally when not able to retrieve change feed, see …
=> Log exception when retrive change feed fails

src/Microsoft.Health.Dicom.Client/DicomWebClient.cs
Disable JsonDicomConverter AutoValidation
Addresses https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=75334
After imported fo-dicom 4.0.7, we can create JsonDicomConverter without AutoValidation
=> [75334]Disable JsonDicomConverter AutoValidation

converter/dicom-cast/samples/templates/default-azuredeploy.json
Update Dicom-Cast ARM template for when not deploying AppInsights. Previously it would fail validation and looking into [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/conditional-resource-deployment#runtime-functions) it looks like even if the resource is not deployed it still tries to reference it. Added a conditional to ensure only references if it is deployed.
#433 
[AB#77695](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/77695)
Ran template to create dicom-cast instances with and without AppInsights.
=> Update Dicom-Cast ARM template

samples/templates/dicomcast-quick-deploy.json
increase min serviceName length=6 so that default-azuredeploy.json does not error out due to too short name (min size = 11) for name+id.
When the serviceName length <= 5 results in an InvalidTemplate error in default-azuredeploy.json.  Increasing size >= 6 resolves this issue.
Manually tested with length 5 and then length 6-8 to verify.
=> increase min name length

.github/dependabot.yml
1. Adds more outstanding PRs to dependabot
2. Enables dependabot on all docker files
3. enables dependabot on github actions
AB#78592
=> enable more dependabot

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Security/SecurityModuleTests.cs, src/Microsoft.Health.Dicom.Api/Modules/SecurityModule.cs, src/Microsoft.Health.Dicom.Core/Configs/AuthenticationConfiguration.cs
This PR updates the code to support having multiple audiences for authentication. It adds a secondary property called `Audiences` that takes precedence over the `Audience` property.
Addresses #505, [AB#78859](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78859)
Added unit tests and manually tested options.
=> Update to support multiple audiences

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/ChangeFeedProcessorTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/FhirTransaction/RetryableFhirTransactionPipelineTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/RetryConfiguration.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/ExceptionStorage/IExceptionStore.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/FhirTransaction/RetryableFhirTransactionPipeline.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/WorkerModule.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.json, converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableExceptionStore.cs
Update the retry policy to retry for a total of 15 times to allow for fhir server to come back up if it is down. It now does exponential back off until it reaches a wait time of 60 seconds, after that it will wait 60 seconds between each retry.
[AB#78067](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78067)
=> [Dicom-Cast] Update retry policy wait time

build/run-e2e-tests.yml, build/run-integration-tests.yml
Update Get-AzKeyValueSecret due to breaking change in latest powershell: Return from Get-AzKeyVaultSecret doesn't have property SecretValueText.
Addresses [AB#80078](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80078)
Test with this run.
=> Update Get-AzKeyValueSecret due to breaking change in latest powershell

src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/DicomDatasetExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/CustomTag/IndexTagTests.cs, src/Microsoft.Health.Dicom.Core/Extensions/DicomDatasetExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/CustomTag/IndexTag.cs, src/Microsoft.Health.Dicom.Core/Features/Store/DicomDatasetValidator.cs, src/Microsoft.Health.Dicom.SqlServer/Features/CustomTag/AddInstanceTableValuedParametersBuilder.cs
1. Remove DicomDatasetExtensions.GetMatchingDicomTags
2. IndexTag consider PrivateCreator when parse into DicomTag
3. Update AddInstanceTableValuePrametersBuilder
Addresses [AB#80426](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80426)
=> Update STOW to support privateCreator

GitVersion.yml, build/.vsts-ci.yml, build/.vsts-pr.yml, build/update-semver.yml
GitVersion seems to be erroneously labeling our main, and part of the effort to fix this is to:
1. Simplify the configuration to only specify what is necessary for mainline development using the GitHubFlow
2. Use the latest Azure Pipelines extension which simply installs and runs the dotnet tool `GitVersion.Tool`
[AB#80668](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80668)
Verify locally and in feature branch PR
=> Refactor GitVersion Usage

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ChangeFeedTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DeleteTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DicomRetrieveMetadataTransactionTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/QueryTransactionTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/StoreTransactionTests.cs
Mark E2E tests with Trait attribute. 
This will be used has a filter to select the tests run in PaaS
[AB#76726](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76726)
dotnet test --filter Category=bvt
=> Categorize tests that will be run in Dicom Service.

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/IndexDataStoreTests.ExtendedQueryTag.cs
[AB#80128](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80128)
=> Integration tests to validate that when instance/series/study is deleted, associated tag data rows are also deleted

build/deploy.yml, src/Microsoft.Health.Dicom.Client/DicomWebClient.cs, src/Microsoft.Health.Dicom.Client/Models/ExtendedQueryTag.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
Enable Extended Query Tag End to end test on PR pipeline
Addresses [AB#80541](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80541)
Locally test pass
=> Enable Extended Query Tag End to end test on PR pipeline

build/analyze.yml
A new tool "detekt" was added to the 1ES SDL tasks and "PublishSecurityAnalysisLogs" automatically checks for it. However, our settings currently throw an error if any task's output is missing. The 1ES team is rolling back this behavior, but in the meantime, we'll reduce this a message in stdout.
N/A
PR pipeline passes
=> Mitigate SDL Bug from Newly Added Tool

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Security/QueryStringValidatorMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Security/QueryStringValidatorMiddleware.cs, src/Microsoft.Health.Dicom.Api/Features/Security/QueryStringValidatorMiddlewareExtension.cs, src/Microsoft.Health.Dicom.Api/Registration/DicomServerApplicationBuilderExtensions.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Exceptions/InvalidQueryStringException.cs, src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj, tools/scale-testing/Common/Common.csproj
This PR adds a query string validator that denies. requests with a `<` or `%3c`
Addresses [AB#79711](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/79711).
New unit tests added.
=> Add query string validator.

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/ExtendedQueryTagControllerTests.cs, src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Exceptions/ExtendedQueryTagFeatureDisabledException.cs
Return BadRequest when ExtendedQueryTag is disabled
Addresses [AB#80934](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80934)
=> Return BadRequest when ExtendedQueryTag is disabled

src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/DeleteExtendedQueryTagServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/DeleteExtendedQueryTagService.cs
Throw ExtendedQueryTagNotFoundException when tag doesn't exist
Addresses [AB#81032](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81032)
=> Throw ExtendedQueryTagNotFoundException when tag doesn't exist

src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/DicomDatasetExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/DicomDatasetValidatorTests.cs, src/Microsoft.Health.Dicom.Core/Extensions/DicomDatasetExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/Store/DicomDatasetValidator.cs, src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/ExtendedQueryTag/AddInstanceTableValuedParametersBuilderTests.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/AddInstanceTableValuedParametersBuilder.cs
When element has different VR than expected, skip both validation and store.
Addresses [AB#81009](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81009)
* All automated tests pass.
* Manually verified bug not repro.
=> When VR doesn't match, skip the dicom element

Directory.Build.props
Updates the healthcare shared packages to version 2.1.4
Addresses [AB#81092](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81092).
Existing tests continue to pass.
=> Update healthcare shared packages to 2.1.4

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Web/Startup.cs
AddDicomBackgroundWorkers to extended on IDicomServerBuilder  instead of IServiceCollection
Addresses [AB#80433](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80433)
All automated test passed
The extension method AddDicomBackgroundWorkers(this IServiceCollection services) should probably extend IDicomServerBuilder instead of IServiceCollection. This could make startUp code more clear.
=> AddDicomBackgroundWorkers to extended on IDicomServerBuilder 

src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomDatasetEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomFileEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomItemCollectionEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomItemEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomPixelDataEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/ExtendedQueryTagEntryEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/ExtendedQueryTagStoreEntryEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/QueryTagComparer.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Common.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Frame.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Series.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Study.cs
Randomize instance identifier of test files, so that never get conflict error  when upload.
Addresses [AB#80262](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/80262)
Locally passed.
=> Fix flaky end to end tests

build/analyze.yml
Remove BinSkim from Secure Development Lifecycle (SDL) pipeline because we do not have unmanaged binaries
[AB#81497](https://microsofthealth.visualstudio.com/Health/_workitems/edit/81497)
Pipelines succeed
=> Clean up SDL Pipeline

src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/AddExtendedQueryTagHandler.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/DeleteExtendedQueryTagHandler.cs, src/Microsoft.Health.Dicom.Core/Features/Security/DataActions.cs
Add ManageExtendedQueryTags data access role for administrate extended query tags
Addresses [AB#81520](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81520)
=> Add ManageExtendedQueryTags data access role for administrate extended query tags

src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DataStoreTestsFixture.cs, tools/dicom-web-electron/main.js
This PR replaces our calls on getting file from `blob.DownloadToAsync` to `blob.OpenReadAsync`. The behavior difference is that the `OpenReadAsync` returns a lazy `Stream` which only starts to download when it is actually being read. Previously, when using `DownloadToAsync` we realize the entire stream in memory. 
The result of this is that our single file read allocations go down significantly, but we we will face more garbage collection as we're not using the `RecyclableMemoryStreamManager` any longer.
In the long term I believe we can strike a balance between which method to use based on file size if we record the dicom file size during the ingestion. 
Addresses [AB#81741](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81741).
Existing …
=> Replace blob.DownloadToAsync with blob.OpenReadAsync

src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/DicomDatasetExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/DicomDatasetValidatorTests.cs, src/Microsoft.Health.Dicom.Tests.Common/Samples.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/StoreTransactionTests.cs
use DicomDataset.NotValidated() instead.
Addresses [AB#81755](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/81755)
Automation test passes locally
=> Remove DicomValidation.AutomationValidation from test code

docs/development/setup.md, src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj, src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs
Adds back health check for background service but move application insights telemetry adding from core to api.
Also fixed a typo in a doc (apparently png and PNG are treated the same in visual studio code but not on github)
=> Add back background service health check

src/Microsoft.Health.Dicom.Api/Features/Context/DicomRequestContextMiddleware.cs, src/Microsoft.Health.Dicom.Core/Features/Context/DicomRequestContext.cs
Currently, correlation id or request id is empty. Hence, there is no way to look at the logs and know about what request the customer is exactly complaining about. This user story should fix that issue.
Following is the pipeline that could be followed. Once the user's request fails, user will look into the logs exposed to them. The logs will have a correlation id or a request id. Customer would tell us the request id that failed. We will look at either `LinuxRequestTelemetry` table or `LinuxExceptionTelemetry` table to get more details about the request. There should be a column called operation id which should correlate to this correlation id or request id field.
[AB#82312](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/82312).
=> Correlation ID / Request ID for Requests.

.dockerignore, build/ci-variables.yml, build/docker-build-push.yml, src/Microsoft.Health.Dicom.Web/Dockerfile, src/Microsoft.Health.Dicom.Web/Startup.cs
- Fix Docker Compose file extension for CI pipeline
- Correctly use .dockerignore file for faster builds
- Fix minor style error
- Set ContinuousIntegrationBuild flag for CI Docker builds
[AB#82320](https://microsofthealth.visualstudio.com/Health/_workitems/edit/82320)
Locally test build and double-check CI name
=> Fix Docker-Compose File Extension for CI

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/2.diff.sql, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlServerSchemaUpgradeTests.cs
This PR updates latest schema migration script(2.diff.sql) for schema migration idempotency.
Currently schema-manager tool runs schema initialization scripts(x.sql) in transaction but runs the migration scripts(x.diff.sql) without wrapping in transaction so this PR ensures that our migration scripts(x.diff.sql) is idempotent.
Addresses [#AB81400](https://microsofthealth.visualstudio.com/Health/_boards/board/t/Resolute/Stories/?workitem=81400)
Integration test is added
=> Make Sql schema migration idempotent

release/scripts/PowerShell/DicomServerRelease/Public/Add-AadTestAuthEnvironment.ps1, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/AuthorizationTests.cs
Revert commenting of grant admin consent, since the AAD team has enable the API back again
[AB#83049](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83049)
E2E should pass
=> Add consent call back and enable the Authorization test

tools/dicom-web-electron/package-lock.json, tools/dicom-web-electron/package.json
- Normalize JSON indent to 2 spaces
- Use npm 7 for `npm install` to update lockfile to v2
N/A
Run tool locally
=> Update lockfile Format to v2 with npm 7

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/3.sql
The schema manager does not run full script in transaction. So making 3.sql re-runnable.
[AB#83514](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/83514)
Run the SQL multiple times.
=> Make full script re-runnable

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/ExtendedQueryTagControllerTests.cs, src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs, src/Microsoft.Health.Dicom.Api/Features/Routing/KnownRoutes.cs, src/Microsoft.Health.Dicom.Core/Extensions/DicomMediatorExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/Audit/AuditEventSubType.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagError.cs, src/Microsoft.Health.Dicom.Core/Messages/ExtendedQueryTag/GetExtendedQueryTagErrorsRequest.cs, src/Microsoft.Health.Dicom.Core/Messages/ExtendedQueryTag/GetExtendedQueryTagErrorsResponse.cs
Add an endpoint for error querying.
GET  `/extendedquerytags/{tagPath}/errors`
Create response body for errors
Addresses [83510](https://microsofthealth.visualstudio.com/Health/_workitems/edit/83510).
Tested through with postman request
Add service
=> Create Extended Query Tag Errors Endpoint

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Api/Registration/JsonMvcBuilderExtensions.cs, src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj, src/Microsoft.Health.Dicom.Core/Registration/JsonServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/DicomAzureFunctionsHttpClientTests.cs, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Microsoft.Health.Dicom.Functions.Client.UnitTests.csproj, src/Microsoft.Health.Dicom.Functions.Client/DicomAzureFunctionsHttpClient.cs, src/Microsoft.Health.Dicom.Functions.Client/Microsoft.Health.Dicom.Functions.Client.csproj, src/Microsoft.Health.Dicom.Functions.Client/Registration/DicomServerBuilderFunctionClientRegistrationExtensions.cs, src/Microsoft.Health.Dicom.Functions.UnitTests/Indexing/ReindexDurableFunctionTests.Trigger.cs, src/Microsoft.Health.Dicom.Functions.UnitTests/Indexing/ReindexDurableFunctionTests.cs, src/Microsoft.Health.Dicom.Functions.UnitTests/Management/DurableClientProxyTests.cs, src/Microsoft.Health.Dicom.Functions.UnitTests/Microsoft.Health.Dicom.Functions.UnitTests.csproj, src/Microsoft.Health.Dicom.Functions/Configuration/DicomBlobContainerConfiguration.cs, src/Microsoft.Health.Dicom.Functions/Indexing/ReindexDurableFunction.Trigger.cs, src/Microsoft.Health.Dicom.Functions/Indexing/ReindexDurableFunction.cs, src/Microsoft.Health.Dicom.Functions/Management/DurableClientProxy.cs, src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj, src/Microsoft.Health.Dicom.Functions/Registration/ServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Functions/Startup.cs, src/Microsoft.Health.Dicom.Functions/host.json, src/Microsoft.Health.Dicom.Metadata/Registration/DicomServerBuilderMetadataRegistrationExtensions.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs
- Fix dependency injection service container to include missing services like the SQL index stores, JSON.NET serializers, and RecycleableMemoryStreamManager
- Normalize serialization between web server and client to use System.Text.Json over JSON.NET in preparation for fo-dicom 5 and .NET 6
N/A
Test locally
=> Fix Re-indexing Dependency Injection

src/Microsoft.Health.Dicom.Api/Configs/DicomServerConfiguration.cs, src/Microsoft.Health.Dicom.Api/Configs/SwaggerConfiguration.cs, src/Microsoft.Health.Dicom.Api/Features/Swagger/ConfigureSwaggerOptions.cs, src/Microsoft.Health.Dicom.Api/Features/Swagger/ErrorCodeOperationFilter.cs, src/Microsoft.Health.Dicom.Api/Features/Swagger/RetrieveOperationFilter.cs, src/Microsoft.Health.Dicom.Api/Features/Swagger/SwaggerDefaultValues.cs, src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Web/appsettings.json
This PR updates the swagger generation in the following ways:
* Moves strings to be config settings, settable via configuration
* Allows for generation of both `yaml` and `json` swagger files.
* Allows for setting a server url in the generated swagger
* Moves swagger classes to `features` folder.
Addresses [AB#84341](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/84341).
Manual testing of generated swagger files.
=> Update swagger generation

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ExtendedQueryTagErrorStoreTests.cs
Delete Extended Query Tag Errors when Corresponding instance is deleted by modifying DeleteInstance stored procedure.
Addresses [User Story 84206](https://microsofthealth.visualstudio.com/Health/_boards/board/t/Medical%20Imaging/Stories/?workitem=84206).
Integration tests
1. Add Tag, Add instance, Add Tag Error
2. Verify instance, Verify Error.
3. Delete instance
4. Verify instance does not exist, verify Error does not exist.
=> Delete XQTE when corresponding Instance is deleted

build/.vsts-ci.yml, build/.vsts-pr.yml, build/build.yml, build/package-nugets.yml, build/package.yml, build/run-integration-tests.yml, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/SchemaVersionConstants.cs
- Make build and publish in linux
- Make windows build for security scan which is slow and make it not depend on environment setup
- Make nuget generation optional and skip it in PR
- Make integration tests run parallel and reduce the SQL schema version supported
[AB#84346](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/84346)
Attached PR build is successfull
=> PR Pipeline optimizations to improve time

build/.vsts-ci.yml, build/.vsts-pr.yml, build/analyze.yml, build/build.yml
- Move Security Analysis to its own dedicated stage that skips building
- Move component governance to the build as it requires a build to analyze dependencies
- Remove Windows build in favor of faster Linux builds
N/A
Test pipelines
=> Speed Up PR and CI Pipelines with Parallel Security Stage

src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Query/SqlQueryGeneratorTests.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryGenerator.cs
- Bug in QIDO-RS paging. Study and Series level queries are not ordered desc during paging.
- Also remove final order by because the results are already ordered during paging.
[AB#85053](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85053)
Added/updated tests on paging generation
=> Add descending to order by and remove the final order by

src/Microsoft.Health.Dicom.Api/Features/Routing/UrlResolver.cs
The comment suggests that requesting `IHttpContextAccessor` has performance implications, based on [this issue](https://github.com/aspnet/Hosting/issues/793). However, the three follow-up comments beginning [here](https://github.com/aspnet/Hosting/issues/793#issuecomment-224828588) clarify that this was speculation.
=> Saving IHttpContextAccessor

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs
Add default value to SP AddExtendedQueryTag for backward compatibility -- allow old binaries work with new SQL schema
Addresses [AB#85211](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85211)
All tests pass.
=> Add default value for backward compatibility

src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs, src/Microsoft.Health.Dicom.Api/Features/Routing/KnownRouteNames.cs, src/Microsoft.Health.Dicom.Api/Features/Routing/UrlResolver.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/GetExtendedQueryTagsServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagErrorReference.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagStoreEntry.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagEntry.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagsService.cs, src/Microsoft.Health.Dicom.Core/Features/Routing/IUrlResolver.cs, src/Microsoft.Health.Dicom.Core/Models/Operations/OperationReference.cs, src/Microsoft.Health.Dicom.Tests.Common/Comparers/ExtendedQueryTagEntryEqualityComparer.cs, src/Microsoft.Health.Dicom.Tests.Common/MockUrlResolver.cs
- Add a new `Errors` object to the `ExtendedQueryTag` resource that will be populated if there is more than 1 error
[AB#85198](https://microsofthealth.visualstudio.com/Health/_workitems/edit/85198)
PR pipeline
=> Add Link to Errors from Extended Query Tag Resource if Present

src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/ExtendedQueryTagErrorsServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Messages/ExtendedQueryTag/GetExtendedQueryTagErrorsRequestTest.cs, src/Microsoft.Health.Dicom.Core/Extensions/DicomMediatorExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagErrorsService.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagErrorsHandler.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/IExtendedQueryTagErrorStore.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/IExtendedQueryTagErrorsService.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/IGetExtendedQueryTagsService.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/PersonNameValidation.cs, src/Microsoft.Health.Dicom.Core/Messages/ExtendedQueryTag/GetExtendedQueryTagErrorsRequest.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/Error/SqlExtendedQueryTagErrorStore.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/Error/SqlExtendedQueryTagErrorStoreV1.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/Error/SqlExtendedQueryTagErrorStoreV4.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ExtendedQueryTagErrorStoreTests.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ExtendedQueryTagStoreTests.cs
- Enable pagination for extended query tag errors with same `limit` and `offset` parameters as QIDO
[AB#85156](https://microsofthealth.visualstudio.com/Health/_workitems/edit/85156/)
PR pipeline
=> Paginate Extended Query Tag Errors

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql
This PR addresses a deadlock issue when issuing a delete command. The stored procedure could encounter a deadlock if the SQL execution plan decided to use a scan instead of a seek while updating the change feed table. This is fixed by using the hint of `FORCESEEK` to always use a seek.
Addresses [AB#85178](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85178).
Manual testing.
=> Add hint for delete instance to use seek instead of scan

src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV2.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV3.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql
Latest binary be able to run run on old Sql Schema(V3)
All end to end tests can run on V3 Sql schema except extended query tags.
=> Latest binary be able to run run on old Sql Schema(V3)

build/.vsts-ci.yml, build/add-aad-test-environment.yml, release/scripts/PowerShell/DicomServerRelease/Public/Add-AadTestAuthEnvironment.ps1, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/DeleteExtendedQueryTagServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/GetExtendedQueryTagsServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ExtendedQueryTag/QueryTagServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagStoreEntry.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/ExtendedQueryTagStoreJoinEntry.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagEntry.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/GetExtendedQueryTagsService.cs, src/Microsoft.Health.Dicom.Core/Features/ExtendedQueryTag/IExtendedQueryTagStore.cs, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/DicomAzureFunctionsHttpClientTests.cs, src/Microsoft.Health.Dicom.Functions.UnitTests/Indexing/ReindexDurableFunctionTests.Activity.cs, src/Microsoft.Health.Dicom.Functions/Indexing/ReindexDurableFunction.Activity.cs, src/Microsoft.Health.Dicom.SqlServer/Extensions/ColumnExtensions.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStore.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV1.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV2.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV4.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ExtendedQueryTagStoreTests.cs
- Return `Operation` for the following APIs:
- `GET /extendedquerytags`
- `GET /extendedquerytags/{tagpath}`
- `PATCH /extendedquerytags/{tagpath}`
- Rename `GetExtendedQueryTagsByOperationAsync` to `GetExtendedQueryTagsAsync`
- Add SQL change to support behavior before release is cut and SQL version bumped
- Include @pengchen0692's fix for build pipelines
[AB#85274](https://microsofthealth.visualstudio.com/Health/_workitems/edit/85274)
Locally and via PR
=> Add Operation to Extended Query Tag Output

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
Disable ExtendedQueryTag E2E tests when using InProc test server.
Ideally we should mark it as skipped instead of pass, xunit does provide  such mechanism  through [`SkipException`](https://github.com/xunit/assert.xunit/blob/main/Sdk/Exceptions/SkipException.cs), but never released, don't know why.
All tests pass
=> Disable ExtendedQueryTag E2E tests when using InProc test server

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/ExtendedQueryTagControllerTests.cs, src/Microsoft.Health.Dicom.Api/Controllers/ExtendedQueryTagController.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/DicomWebConstants.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/Models/ExtendedQueryTagError.cs, src/Microsoft.Health.Dicom.Client/Models/ExtendedQueryTagErrorReference.cs, src/Microsoft.Health.Dicom.Client/Models/GetExtendedQueryTagEntry.cs, src/Microsoft.Health.Dicom.Functions/host.json, src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/InstanceStoreTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomTagsManager.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
- Update `IDicomWebClient` with new paginated APIs for getting extended query tags and their errors
- Update data models to incorporate references to operation and errors
- Fix errors return type and DI
- Update E2E test
N/A
Via local client testing
=> Update IDicomWebClient for Extended Query Tags + Errors

Directory.Build.props, src/Microsoft.Health.Dicom.Web/appsettings.json
Set the Blob httpClient ConnectTimeout to 2 seconds read from appSettings.
[AB#85137](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85137)
SocketHandler ConnectTimeout is set correct.
Zeiss will help test the QIDO performance
=> Set Http/Https connectTimeout to 2 seconds for Blob connections

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/4.sql, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlServerSchemaUpgradeTests.cs
- Fix 4.sql to be idempotent
- Enforce idempotency through new integration test
[AB#85322](https://microsofthealth.visualstudio.com/Health/_workitems/edit/85322)
Tested via pipeline
=> Fix SQL Snapshot Scripts to be Idempotent

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlDataStoreTestsFixture.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlServerSchemaUpgradeTests.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlTestUtils.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/StoredProcedureCompatibleValidator.cs
There is small window where Sql schema is updated but not populated to web server, so the server still tries to call old stored procedure. This test validate it works by checking stored procedure compatiblity.
Addresses [AB#85211](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85211).
All tests pass
=> Add test to validate if stored procedure in new Sql schema compatible with old one

Directory.Build.props
Update sdkpackageversion to 5.0.9 to solve governance alert.
Addresses [AB#85404](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85404)
All tests passed
=> Update sdkpackageversion to 5.0.9 to solve governance alert.

src/Microsoft.Health.Dicom.Api/Features/Partition/DataPartitionFeatureValidatorService.cs, src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Partition/PartitionCacheTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Exceptions/DataPartitionsFeatureCannotBeDisabledException.cs, src/Microsoft.Health.Dicom.Core/Features/Partition/PartitionCache.cs, src/Microsoft.Health.Dicom.Core/Features/Partition/PartitionService.cs, src/Microsoft.Health.Dicom.Core/Modules/ServiceModule.cs, src/Microsoft.Health.Dicom.Web/Startup.cs, src/Microsoft.Health.Dicom.Web/appsettings.Development.json
This PR includes changes to ensure user cannot disable DataPartitions feature flag if they already created partitioned data other than the default partition.
Addresses [[AB#85406](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85406)].
=> Data partitions - Ensure feature cannot be disabled when data is partitioned

test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/InProcTestDicomWebServer.cs
Currently E2E tests are failing locally due to data partition tests using same DB. This PR uses a different DB for data partition enabled tests
Addresses [[AB#86511](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/86511)].
Ran local tests to ensure tests are passed
=> Fix broken E2E test due to data partitions validation

src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Schema/VersionedCacheTests.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/VersionedCache.cs
Current versioned schema resolver returns the exact matching versioned entity. If there is no changes to the stored procedure, then all the stores needs to be incremented. This change will return the closest matching entity which is greater than or equal to the min version.
Addresses [[AB#85996](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85996)].
Unit testing is added to ensure correctness
=> Update schemaresolver to return closest matching versioned entity

build/package-nugets.yml, src/Microsoft.Health.Dicom.Core/Features/Validation/ValidationErrorCode.cs, src/Microsoft.Health.Dicom.Tests.Common/Microsoft.Health.Dicom.Tests.Common.csproj
- Add symbol indexing for Dicom NuGet packages
- Fix `Microsoft.Health.Dicom.Tests.Common` dependencies
- Edit `ValidationErrorCode` XML and `ImplicitVRNotAllowed` value
[AB#78417](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/78417)
Packed locally
=> Add Symbol Indexing and Fix Test Package Publish

build/build.yml, build/package-nugets.yml, build/publish-nuget.yml
- Move symbol publish to the existing nuget publish stage that runs on Windows VMs
N/A
Ad-hoc run of CI without publish
=> Publish Symbols in Windows Stage

docs/resources/conformance-statement.md
This corrects two small errors in the store (STOW-RS) section of the DICOM conformance statement.
1. The tags for `ReferencedSOPInstanceUID` were incorrect, and should be [(0008, 1155)](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_10.8.html#table_10-11)
2. The description for the successful set described it as containing the failed instances.
None
N/A; I don't think this document is linked to any other generated documentation.
=> Correct tag and descriptions in Store section of the Conformance Statement

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Context/DicomRequestContextMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Context/DicomRequestContextMiddleware.cs, src/Microsoft.Health.Dicom.Core/Features/Context/IDicomRequestContext.cs
This calculation will now be done in workspace platform code. Due to the order of execution of the middleware, this was only being run after billing middleware had finished, so it would not get the response size
PR in workspace platform - https://microsofthealth.visualstudio.com/Health/_git/workspace-platform/pullrequest/17048
Addresses [#87344].
Ran unit tests
=> Remove response size calculation from request middleware

Directory.Build.props, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/AuthenticationConfiguration.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Extensions/IHttpClientBuilderRegistrationExtensions.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/ServiceCollectionExtensions.cs
This PR brings in the latest version of the shared components and adds support for the client certificate credentials to DICOM Cast.
Addresses [AB#87283](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87283).
Manual testing.
=> Add support to client certificate credentials to dicom cast.

Microsoft.Health.Dicom.sln, build/deploy.yml, build/package.yml, samples/templates/default-azuredeploy.json, src/Microsoft.Health.Dicom.Functions.Hosting/Microsoft.Health.Dicom.Functions.Hosting.csproj, src/Microsoft.Health.Dicom.Functions.Hosting/Properties/AssemblyInfo.cs, src/Microsoft.Health.Dicom.Functions.Hosting/Startup.cs, src/Microsoft.Health.Dicom.Functions.Hosting/host.json, src/Microsoft.Health.Dicom.Functions.Hosting/local.settings.json, src/Microsoft.Health.Dicom.Functions/Microsoft.Health.Dicom.Functions.csproj
By having a reference to `Microsoft.NET.Sdk.Functions` the `Microsoft.Health.Dicom.Functions` project will not pack into a nuget. This will cause any downstream dependency on `Microsoft.Health.Dicom.Web.Tests.E2E` to not restore properly since a dependency cannot be resolved.
Addresses [AB#87579](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87579).
Manually ran `dotnet pack` against `Microsoft.Health.Dicom.Functions`
=> Update Microsoft.Health.Dicom.Functions to dotnet pack.

test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstanceId.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/Audit/AuditTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ChangeFeedTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DataPartitionEnabledTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DeleteTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DicomRetrieveMetadataETagTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/DicomRetrieveMetadataTransactionTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HttpIntegrationTestFixture.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/QueryTransactionTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Common.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Frame.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Series.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Study.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/StoreTransactionTests.cs
Cleanup test dicom instances after tests complete 
Addresses [AB#85819](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/85819)
Locally tests verify no test instances after test complets
=> Cleanup test dicom instances after tests complete

.github/dependabot.yml, tools/dicom-web-electron/package-lock.json
As per the [alert] (https://github.com/microsoft/dicom-server/security/dependabot/tools/dicom-web-electron/package-lock.json/follow-redirects/open), follows-redirect version has been updated to 1.14.7.
=> Fix Dependabot Alert

tools/dicom-web-electron/package-lock.json
Updating remaining follow-redirect dependencies in order to resolve the dependabot security alert.
[AB#87864](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87864).
=> Fix for Dependabot Alert.

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/JsonSerializerOptionsExtensionsTests.cs, src/Microsoft.Health.Dicom.Core/Extensions/JsonSerializerOptionsExtensions.cs, src/Microsoft.Health.Dicom.Operations/Registration/ServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Tests.Common/Serialization/AppSerializerOptions.cs
- Expand the set of specified JSON serializer options for stricter API contracts
- Centralize the options for consistent rules across services
N/A
Pipeline + New tests
=> Centralize and Expand Json Serializer Options

src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj, test/Microsoft.Health.Dicom.Tests.Integration/Microsoft.Health.Dicom.Tests.Integration.csproj
It is replaced already with the new Microsoft.Data.SqlClient
[AB#88198](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88198)
Existing tests pass
=> Remove old SQL client(system.Data.SqlClient) package reference

Microsoft.Health.Dicom.sln, src/Microsoft.Health.Dicom.Api/Controllers/OperationsController.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Reference.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Store.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.Reference.cs, src/Microsoft.Health.Dicom.Client/Microsoft.Health.Dicom.Client.csproj, src/Microsoft.Health.Dicom.Client/Models/ExtendedQueryTagErrorReference.cs, src/Microsoft.Health.Dicom.Client/Models/IResourceReference.cs, src/Microsoft.Health.Dicom.Client/Models/OperationReference.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomTagsManager.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
The `OperationsController` was missing version attributes, so it only accepted the latest one.
- Add `v1-prerelease` and `v1` support for the `OperationsController`
- Refactor "reference" models in the client project such that the client can easily retrieve the URL
- Refactor Json serializer options to be `static`
- Return `IReadOnlyList<T>` for XQT endpoints
- Validate URIs in e2e tests
- Fix build configuration for docker compose project
[AB#86795](https://microsofthealth.visualstudio.com/Health/_workitems/edit/86795)
Tested via pipeline and postman
=> Fix v1-Prerelease Version for Operations Controller

docs/resources/conformance-statement.md, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/DicomStoreServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreDatasetValidatorTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Validation/ImplicitValueRepresentationValidatorTests.cs, src/Microsoft.Health.Dicom.Core/Features/Store/FailureReasonCodes.cs, src/Microsoft.Health.Dicom.Core/Features/Store/IStoreDatasetValidator.cs, src/Microsoft.Health.Dicom.Core/Features/Store/IStoreResponseBuilder.cs, src/Microsoft.Health.Dicom.Core/Features/Store/StoreDatasetValidator.cs, src/Microsoft.Health.Dicom.Core/Features/Store/StoreResponseBuilder.cs, src/Microsoft.Health.Dicom.Core/Features/Store/StoreService.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/ImplicitValueRepresentationValidator.cs
Treat the "Implicit VR not allowed" validation failure as "Warning".
Addresses [issue #]. [AB#88125](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88125)
Added Unit Test coverage
=> Treat the "Implicit VR not allowed" validation failure as "Warning"

src/Microsoft.Health.Dicom.Core/Features/Workitem/IIndexWorkitemStore.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemOrchestrator.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/9.diff.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/9.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Model/VLatest.Generated.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/AddWorkitem.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Sprocs/UpdateWorkitemStatus.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Sql/Tables/Workitem.sql, src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStore.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStoreV9.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/WorkitemTests.cs
This PR includes changes that will save workitem in two step. First it will create the workitem record in the DB with Creating status and after the blob upload is successful it will update the status to Created.
For Retrieve and search transaction only Created status workitem are returned back.
Addresses [[AB#87263](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87263)].
Integration tests added to ensure workitem is added.
=> Two step adding workitem

src/Microsoft.Health.Dicom.Core/Features/Retrieve/FrameHandler.cs
When retrieving a frame, forces reading all pixel data as a workaround while we await the fix from fo-dicom.
Addresses [AB#87723](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87723), #1248
All tests pass.
=> Read all data from Dicom file when retrieving a frame.

README.md
The link to DICOM Web was broken and is updated to point to the right URL. The Deploy to Azure button is also updated to correct URL.
Addresses [issue #1349]
Manual
=> Link and logo url updates

src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Schema/VersionedCacheTests.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/VersionedCache.cs
The `VersionedCache<T>` errroneously prevents store implementations whose version predates the minimum from being used.
Fixes [AB#88740](https://microsofthealth.visualstudio.com/Health/_workitems/edit/88740)
Update tests with values that are less than the minimum
=> Allow Store Implementations whose Versions are Less than the Minimum

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/SqlServerSchemaUpgradeTests.cs
These tests currently run against every version since the minimum supported, which contributes significantly to the integration test runtime in PR and CI. The past versions have already passed this test, don't need to be re-tested.
Runs these tests only against the max schema version, and the -1 version for diffs.
Addresses [AB#88752](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88752).
Tests pass.
=> Run SQL schema integration tests against current changes

src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryParser.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Query.cs
Removes references to QIDO-RS in error messages that are generic to all search transactions, and small edits for grammar and readability to other messages.
Only resource files changed.
=> Error message cleanup

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/WorkitemQueryParserTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/WorkitemQueryResponseBuilderTests.cs, src/Microsoft.Health.Dicom.Core/Features/Query/QueryLimit.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryResponseBuilder.cs
Moves the list of required return attributes when searching for workitems to the response builder and revises the list to match the standard.
Addresses [AB#88986](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/88986).
Added new unit tests covering more return cases.
=> Move required workitem return attributes to response builder

converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableClientReadWriteTestProvider.cs
This PR updates the Dicom Cast table health check to remove deleting the table as part of the check. This operation could take up to 40 seconds to complete and during a subsequent health check it would fail as the table was in the process of being deleted.
Addresses [AB#89298](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/89298)
Manually pull downstream and tested.
=> Update DICOM Cast Table Health Check

docs/concepts/worklist.md, docs/resources/data-partition-feature.postman_collection.json, src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Controllers/WorkitemController.Cancel.cs, src/Microsoft.Health.Dicom.Api/DicomApiResource.Designer.cs, src/Microsoft.Health.Dicom.Api/DicomApiResource.resx, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Workitem.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.Workitem.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/CancelWorkitemDatasetValidatorTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Extensions/DicomDatasetExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/CancelWorkitemRequestHandler.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Cancel.cs
- adds docs for request cancel and queryable study instance UID
- adds a Postman request
- adds the warning header to a request where the workitem is already cancelled
- handles JSON serialization exceptions as 400 instead of 500
- makes conditional final state requirements default to false since they are not required by default
- accepts an IEnumerable of datasets
- updates client to do the same.
All tests pass, a number of test updated and added.
=> Small changes to request cancellation

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/WorkitemQueryParserTests.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryParser.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryResponseBuilder.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Query.cs
Add support for querying the same DICOM tag under a different sequence.
Addresses [AB#89340](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/89340).
Added unit test to validate the scenario and also added additional E2E tests.
=> Support querying same tag under a sequence

.github/workflows/combine-dependabot-prs.yml
This action doesn't check all statuses accurately - this change should check all statuses in all contexts: https://docs.github.com/en/rest/reference/commits#get-the-combined-status-for-a-specific-reference
Manual testing
=> updating dependabot action to check combined status

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExtendedQueryTagTests.cs
CI has 2 flaky tests that fails. Skip these tests, to be fixed with mentioned bug
[AB#90068](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/90068)
NA
=> Skip two flaky extendedQueryTag tests.

.github/workflows/combine-dependabot-prs.yml
This Github Action only checks the status of pr branches, but we run many [checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#types-of-status-checks-on-github) that all should be passing - ADO pipelines triggered by the Azure Dev Ops app is a check rather than a status. Added logic to check that all check suites are passing, but also to ignore dependabot checks, since they are queued but never seem to run.
Manual
=> Fix dependabot GitHub action to look at checks

docs/concepts/worklist.md, src/Microsoft.Health.Dicom.Api/Controllers/WorkitemController.Query.cs, src/Microsoft.Health.Dicom.Api/Extensions/WorkitemResponseStatusExtensions.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Workitem/WorkitemQueryResponseBuilderTests.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/Model/WorkitemInstanceIdentifier.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemOrchestrator.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryResponseBuilder.cs, src/Microsoft.Health.Dicom.Core/Messages/WorkItem/QueryWorkitemResourceResponse.cs, src/Microsoft.Health.Dicom.Core/Messages/WorkItem/WorkitemResponseStatus.cs
This PR handles the conflict that could while querying workitems and return partial content if in case it is not able to find the result dataset.
Addresses [AB#90099](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/90099).
Added unit tests
=> Return partial content for query workitems

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs, src/Microsoft.Health.Dicom.Core/Features/HealthCheck/BackgroundServiceHealthCheck.cs
This PR updates the `ExceptionHandlingMiddleware` to handle cases when the client has closed the connection. It now sets a status of `BadRequest` vs the previously recorded `InternalServerError`. 
Addresses [AB#90280](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/90280).
Added unit test, manually tested with local connection closed and downstream implementations.
=> Add cases for connection closed exceptions

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs
Had moved the swagger to dev only in this PR https://github.com/microsoft/dicom-server/pull/1364/files#diff-dd43c40853387d56010cb41f7edfe564e9b891711897f35fc3c904af0aecfb12
Looks like we have a dependency on this being in prod for URSA scan
[AB#91363](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/91363)
NA
=> Move swagger api out of dev to support URSA scan

src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/ConfigurationBinderExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/JsonSerializerOptionsExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Extensions/JsonSerializerSettingsExtensionsTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Microsoft.Health.Dicom.Core.UnitTests.csproj, src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/ConfigurationJsonConverterTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/DicomIdentifierJsonConverterTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/Newtonsoft/ConfigurationJsonConverterTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Extensions/ConfigurationBinderExtensions.cs, src/Microsoft.Health.Dicom.Core/Extensions/JsonSerializerOptionsExtensions.cs, src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj, src/Microsoft.Health.Dicom.Core/Models/Indexing/ReindexCheckpoint.cs, src/Microsoft.Health.Dicom.Core/Models/Operations/BatchingOptions.cs, src/Microsoft.Health.Dicom.Core/Serialization/ConfigurationJsonConverter.cs, src/Microsoft.Health.Dicom.Core/Serialization/DicomIdentifierJsonConverter.cs, src/Microsoft.Health.Dicom.Core/Serialization/Newtonsoft/ConfigurationJsonConverter.cs, src/Microsoft.Health.Dicom.Functions.Client/Registration/DicomServerBuilderFunctionClientRegistrationExtensions.cs, src/Microsoft.Health.Dicom.Functions/Indexing/ReindexDurableFunction.Orchestration.cs, src/Microsoft.Health.Dicom.Functions/Registration/ServiceCollectionExtensions.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Microsoft.Health.Dicom.Web.Tests.E2E.csproj
- Add new `Set` method to mirror the `Get` method implemented by the Configuration Binder
- Add new `JsonConverter` for `DicomIdentifier`
- Refactor how strings are generated for the `IConfiguration` `JsonConverter`
- Load Json.NET serialization settings from options instead of Durable Task defaults
Addresses [AB#90232](https://microsofthealth.visualstudio.com/Health/_workitems/edit/90232)
Addresses [AB#91160](https://microsofthealth.visualstudio.com/Health/_workitems/edit/91160)
New unit tests
=> Refactor Json.NET Serialization and Add Configuration Binder Set Method

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/DicomWebConfiguration.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Modules/DicomModule.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.Development.json, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.json
Allows dicomcast to talk to dicom through a private endpoint in PaaS solution while still using public endpoint when creating fhir resources.
[AB#91414](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/91414)
After a long hard fought war with health-PaaS this was tested end to end in a personal cluster using a personal resource provider. 
Validated that it talked to private dicom endpoint and that fhir urls still had public endpoints
=> Allow Dicom Cast to communicate with private endpoint

src/Microsoft.Health.Dicom.Api.UnitTests/Features/BackgroundServices/DeletedInstanceCleanupWorkerTests.cs, src/Microsoft.Health.Dicom.Api/Features/BackgroundServices/DeletedInstanceCleanupWorker.cs, src/Microsoft.Health.Dicom.Core/Exceptions/DataStoreNotReadyException.cs, src/Microsoft.Health.Dicom.Core/Features/HealthCheck/BackgroundServiceHealthCheck.cs, src/Microsoft.Health.Dicom.SqlServer.UnitTests/Features/Schema/VersionedCacheTests.cs, src/Microsoft.Health.Dicom.SqlServer/Exceptions/InvalidSchemaVersionException.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Schema/VersionedCache.cs
This PR changes how we handle `InvalidSchemaVersionException` in two different cases. Each one is a case where the service doesn't yet know what the current schema version is on startup and we should be resilient to this.
- `DeletedInstanceCleanupWorker` - If this is the case, we should ignore this exception and continue to process on our normal cadence
- `BackgroundServiceHealthCheck` - Return an unhealthy result since this exception would constitute that we're unhealthy.
Addresses [AB#90262](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/90262).
Unit test added for cleanup worker.
=> Handle InvalidSchemaVersionException

NOTICE.md, src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj, src/Microsoft.Health.Dicom.Blob/Utilities/HashingHelper.cs
This reverts commit 795d2d5854e4975b59c557a47cada34a3baeeae0.
Reverting the hashing change since it will break the compat. The methods are not returning the same value.
=> Revert "Change to IO.Hashing"

src/Microsoft.Health.Dicom.Client/DicomWebClient.Workitem.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.Workitem.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/ChangeWorkitemStateRequestHandler.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.ChangeState.cs
Fix to handle Enumerable DicomDataset in the request payload for Change Workitem State.
Addresses [[AB#87271](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/87271)]
All existing tests pass.
=> Fixes to handle Enumerable Dataset in the Request Payload for Change Workitem State API

docs/resources/Conformance-as-Postman.postman_collection.json
Added a "POST AuthorizeGetToken" call for obtaining an access token
Renamed "POST Store-single-instance (red-triangle.dcm)"
Reverted single instance paths back to original
Restored 'raw' option for dicom files in single instance calls
=> Updated Conformance-as-Postman.postman_collection.json

src/Microsoft.Health.Dicom.Api/Features/Filters/PopulateDataPartitionFilterAttribute.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Exceptions/InvalidIdentifierExceptionTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Exceptions/DataPartitionsNotFoundException.cs, src/Microsoft.Health.Dicom.Core/Exceptions/ElementValidationException.cs, src/Microsoft.Health.Dicom.Core/Exceptions/InvalidIdentifierException.cs, src/Microsoft.Health.Dicom.Core/Exceptions/InvalidPartitionNameException.cs, src/Microsoft.Health.Dicom.Core/Features/Store/StoreDatasetValidator.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/DateValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/ElementMaxLengthValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/ElementRequiredLengthValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/EncodedStringElementValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/LongStringValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/PartitionNameValidator.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/PersonNameValidation.cs, src/Microsoft.Health.Dicom.Core/Features/Validation/UidValidation.cs
Remove remaining UIDs and partition names from logs which will not be redacted through PaaS solution.
AB#[92521](https://microsofthealth.visualstudio.com/Health/_workitems/edit/92521).
All the tests are passing.
Query that can later be used to verify if this pull request solved the problem:
```
LinuxTraceTelemetry
| where TIMESTAMP > ago(3d)
|where cloud_RoleName == "dicom"
|where message !contains "404"
|where message !contains "403"
| distinct message
```
=> Remove remaining UIDs and partition names from logs

src/Microsoft.Health.Dicom.Client/DicomWebClient.ChangeFeed.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Operation.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Partition.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Store.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Workitem.cs
Some client methods required partition, which should never be the case. While here I also made all cancellation tokens optional.
Addresses [AB#92838](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/92838)
All tests pass.
=> Making partition name and cancellation token optional across client

src/Microsoft.Health.Dicom.SchemaManager/Microsoft.Health.Dicom.SchemaManager.csproj
This fixes an error introduced with the new DICOM SchemaManager project due to its dependency on the preview-only NuGet package System.CommandLine.
=> Added NoWarn for SchemaManager System.CommandLine dependency.

docker/sql/Dockerfile
- Update Focal image digest
- Use `focal` tag instead to dissuage dependabot from updating to later editions of Ubuntu
N/A
Pipeline
=> Update Focal Image

Directory.Build.props, Microsoft.Health.Dicom.sln, src/Microsoft.Health.Dicom.SchemaManager/DicomBaseSchemaRunner.cs, src/Microsoft.Health.Dicom.SchemaManager/DicomSchemaClient.cs, src/Microsoft.Health.Dicom.SchemaManager/SchemaManagerServiceCollectionBuilder.cs
Previously there was a dependency on a copy of the DICOM service to be running when the Schema Manager was executing. This PR updates this to capture specific exceptions that are thrown when there is no instance running when the schema manager is running. The assumption is that if there is no instance registered with the DB then it is safe to pursue the upgrade to the specified version.
Addresses [AB#93113](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93113).
Manual testing with local instances and also downstream testing.
=> Update DICOM Schema Manager to run with empty DB

docs/resources/conformance-statement.md, src/Microsoft.Health.Dicom.Api/Controllers/RetrieveController.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Retrieve.cs, src/Microsoft.Health.Dicom.Client/IDicomWebClient.Retrieve.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveResourceServiceTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveTransferSyntaxHandler.cs, src/Microsoft.Health.Dicom.Tests.Common/AcceptHeaderHelpers.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Frame.cs
Add support allow single part get on frame
Accept: application/octet-stream; transfer-syntax=*
[AB#93653](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93653)
New E2E and unit test added
=> Support single part frame get

Directory.Packages.props, src/Microsoft.Health.Dicom.SchemaManager.Console/Microsoft.Health.Dicom.SchemaManager.Console.csproj, src/Microsoft.Health.Dicom.SchemaManager.Console/Program.cs, src/Microsoft.Health.Dicom.SchemaManager.Console/Properties/launchSettings.json, src/Microsoft.Health.Dicom.SchemaManager.Console/appsettings.json, src/Microsoft.Health.Dicom.SchemaManager/CommandCollectionExtensions.cs, src/Microsoft.Health.Dicom.SchemaManager/SchemaManagerParserBuilder.cs, src/Microsoft.Health.Dicom.SchemaManager/SchemaManagerServiceCollectionBuilder.cs
This PR adds the ability to have different configuration providers for Schema Manager. Additionally it refactors the extensions provided to allow it to be used in way to add additional service providers.
Addresses [AB#93339](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93339).
Manually tested in OSS and downstream.
=> Add additional config options to SchemaManager

Directory.Build.props, Directory.Packages.props, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Program.cs, src/Microsoft.Health.Dicom.Web/Startup.cs
…shared across multiple libraries. This version of Application Insights marks instrumentation key as obsolete - we will build connection strings with the instrumentation key in Dicom and DicomCast: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2560
Tracked via [AB#93836](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93836)
Tested by sending telemetry to Application Insights via the new configuration.
=> Adding a new prop to track the Application Insights package version

converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/DicomCastWorker.cs
Flush the metrics when appliation crashes
Addresses [issue #93947](https://microsofthealth.visualstudio.com/Health/_backlogs/backlog/Medical%20Imaging/Epics/?workitem=93947)
Tested in test environment.
=> Flush metrics

src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs, src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobMetadataStore.cs, src/Microsoft.Health.Dicom.Core/Configs/BlobMigrationConfiguration.cs
When enabled, this setting will log usage of the old blob format to assist in understanding the extent and completion of a blob format migration. There is minor code duplication in the logging methods, but until / unless we refactor these clients, that seems like the most pragmatic approach.
Addresses [AB#93278](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93278)
=> Adding a configuration setting to log usage of the old blob format.

converter/dicom-cast/src/Microsoft.Health.DicomCast.TableStorage/Features/Storage/TableExceptionStore.cs
Pods were restarting while dicomcast processes change feed entries for Delete resources that has multiple resource matches in Fhir. The issue was due to the metadata field being blank in Delete changefeed entries. 
Addresses [issue #331589309](https://portal.microsofticm.com/imp/v3/incidents/details/331589309/home).
- Run the fhir, dicom and dicomcast apps in local. 
- Delete an image in dicom using the DELETE study endpoint that has multiple entries in Fhir. 
- Make sure there are no null reference exceptions while dicomcast processes the change feed entry
=> Fix for null reference issue while dicomcast processes erred DELETE entries

tools/uploader-function/src/DicomUploaderFunction/DicomUploaderFunction.csproj
- Use latest blob storage SDK to resolve CVE-2022-30187 in uploader function
N/A
Existing tests
=> Fix CVE-2022-30187 for Uploader Function

docker/docker-compose.yml, docs/how-to-guides/export-data.md, samples/templates/default-azuredeploy.json, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/HealthChecks/DurableTaskHealthCheckTests.cs, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Microsoft.Health.Dicom.Functions.Client.UnitTests.csproj, src/Microsoft.Health.Dicom.Functions.Client/HealthChecks/DurableTaskHealthCheck.cs, src/Microsoft.Health.Dicom.Functions.Client/Microsoft.Health.Dicom.Functions.Client.csproj, src/Microsoft.Health.Dicom.Functions.Client/Registration/DicomServerBuilderFunctionClientRegistrationExtensions.cs, src/Microsoft.Health.Dicom.Web/appsettings.Development.json, src/Microsoft.Health.Dicom.Web/appsettings.json
- Add new durable task health check to ensure calls aren't made to the service before the underlying task hub has been initialized
- Update export docs
- Enable export by default
[AB#94982](https://microsofthealth.visualstudio.com/Health/_workitems/edit/94982/)
Added new tests
=> Add Durable Task Health Check

Directory.Build.props, Directory.Packages.props, forks/Microsoft.Health.FellowOakDicom/Microsoft.Health.FellowOakDicom.csproj, lang/IsExternalInit.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.ExtendedQueryTag.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.Store.cs, src/Microsoft.Health.Dicom.Client/DicomWebClient.cs, src/Microsoft.Health.Dicom.Client/Microsoft.Health.Dicom.Client.csproj
- Add .NET Standard 2.0 target to client
- Add build properties necessary to support future C# language feature "polyfills"
N/A
N/A
=> Add .NET Standard 2.0 Target to Dicom Client

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs
Currently, a request that is cancelled by the client will throw a `TaskCanceledException` in the blob libraries that is wrapped in a `DataStoreException`. This change will return 400 Bad Request in this case rather than a 500.
Addresses AB#95767
Added a unit test.
=> Handling DataStoreExceptions when caused by a TaskCanceledException

forks/Microsoft.Health.FellowOakDicom/Serialization/JsonDicomConverter.cs, src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs
Handle ArgumentException in the Exception handler middleware and return BadRequest (400) error.
Addresses [[AB#95663](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/95663)].
Added ArgumentException in the list of Exception data to be tried in the test coverage
=> [AB#95663] fix for Unhandled System.ArgumentException when creating workitem

converter/dicom-cast/samples/templates/default-azuredeploy.json, converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json
Adding the mandatory parameters (patientSystemId and isIssuerIdUsed) that are required in default-azuredeploy.json
Addresses bug [95894](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/95894).
Provisioned a personal environment using the new sample ARM template and verified whether the validation is successful.
=> Updated deployment template to include patient system id changes

Directory.Packages.props, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/HealthChecks/DurableTaskHealthCheckTests.cs, src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Microsoft.Health.Dicom.Functions.Client.UnitTests.csproj, src/Microsoft.Health.Dicom.Functions.Client/HealthChecks/DurableTaskHealthCheck.cs, src/Microsoft.Health.Dicom.Functions.Client/Microsoft.Health.Dicom.Functions.Client.csproj
Refactor the Durable Task health check to validate Azure Blob, Queue, and Table service connections
[AB#94982](https://microsofthealth.visualstudio.com/Health/_workitems/edit/94982)
Refactored tests
=> Fix Durable Task Health Check to Validate all Services

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryParserTests.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.Designer.cs, src/Microsoft.Health.Dicom.Core/DicomCoreResource.resx, src/Microsoft.Health.Dicom.Core/Features/Query/BaseQueryParser.cs, src/Microsoft.Health.Dicom.Core/Features/Query/QueryParser.cs, src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemQueryParser.cs
Qido query with PatienName=Thoma"s&FuzzyMatching=True throws 500 error
This because double quote is a invalid char in any fuzzy matching(word or phrase) in SQL.
Since this a fuzzy matching it needs to be a word or phrase and we should not replace the quote with any character.
Error will recommend customer to do exact match or try a simple word with fuzzy match. Which will help the customer to have better success.
[AB#96513](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/96513)
Unit test added
=> Throw 400 on quotes character in query filter condition with fuzzymatch

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveResourceServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs, test/Microsoft.Health.Dicom.Tests.Integration/Features/RetrieveResourceServiceTests.cs
Based on the doc https://github.com/microsoft/dicom-server/blob/main/src/Microsoft.Health.Dicom.Blob/AzureBlobAPIs.md
[AB#96577](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/96577)
Existing tests pass.
=> Move wado resource get without transcoding to new blob network api to reduce buffer copy and possible reduce cpu cycle

src/Microsoft.Health.Dicom.SqlServer/Features/ChangeFeed/SqlChangeFeedStoreV24.cs
Handle dbNull for cleanup operation. 
This PR changes doesn't affect the existing but checking in to have bug free code.
Addresses [issue [AB#98482](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/98482)].
=> Handle dbNull for Cleanup operation

tools/file-generator-tool/Microsoft.Health.Dicom.FileGenerator/Microsoft.Health.Dicom.FileGenerator.csproj
Following the existing pattern, we are ignoring `NU5104` in order to use System.CommandLine in tools that aren't part of the main service.
=> Disabling warning for System.CommandLine

src/Microsoft.Health.Dicom.Functions.Client/HealthChecks/DurableTaskHealthCheck.cs
Cancelled storage operations [sometimes throw](https://github.com/Azure/azure-storage-net/issues/512) a StorageException wrapping an OperationCanceledException (or the child TaskCanceledException).
The Azure Webjobs framework [catches these exceptions](https://github.com/Azure/azure-webjobs-sdk/pull/1273) but we encounter this case because we use the DurableTask clients directly via reflection. 
Here we throw the inner exception, which is [expected by ASP.NET Core's DefaultHealthCheckService](https://github.com/dotnet/aspnetcore/blob/9cbf44b7c192cf064a82934bbf479a93a1953c26/src/HealthChecks/HealthChecks/src/DefaultHealthCheckService.cs#L121), while [maintaining the stack trace of the inner exception](https://learn.microsoft.com/en-us/archive/msdn-magazine/2015/november/essential-net-csharp …
=> Catching task cancelled exceptions from WindowsAzure.Storage

src/Microsoft.Health.Dicom.SqlServer/Features/ChangeFeed/SqlChangeFeedStoreV24.cs
Fix DbNull issue when there is no watermark in changefeed table. The operation won't be executed but just keeping the code clean
Addresses [issue [AB#98482](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/98482)].
=> Handle DBNull to fix log issues

src/Microsoft.Health.Dicom.Functions.Client.UnitTests/TaskHub/TrackingTableTests.cs, src/Microsoft.Health.Dicom.Functions.Client/TaskHub/TrackingTable.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HealthCheckTests.cs
Strangely, there have been some regressions and differences between Azurite and the real Azure Table Service's OData behavior. Specifically, previous versions of Azurite accepted the query `PartitionKey eq null` while the Azure Table Service currently rejects it. This has since been fixed in the latest version. Furthermore, Azurite currently rejects the query `false` while the Azure Table Service currently accepts this query. This bug in Azurite appears to be fixed now but has yet to be unreleased.
Therefore, we'll change the query to one that is unlikely to return results, before eventually changing the query to `false` in the future once acceptable in Azurite. Furthermore, with the addition of health check tests, we'll assert the behavior in both Azurite during PRs and the real Azure …
=> Fix Table Service Query

src/Microsoft.Health.Dicom.Functions.Client.UnitTests/Extensions/AzureComponentFactoryExtensionsTests.cs, src/Microsoft.Health.Dicom.Functions.Client/Extensions/AzureComponentFactoryExtensions.cs, src/Microsoft.Health.Dicom.Functions.Client/TaskHub/AzureStorageTaskHubClient.cs
Azure Functions allows for the use of `accountName` to specify the storage account as well as the specification of each storage service using `blobServiceUri`, `queueServiceUri`, and `tableServiceUri`. However, the `AzureComponentFactory` only expects either a connection string (via the section value or `connectionString`) or `serviceUri`. In this change, we add support for directly supplying the per-service URIs or the account name.
N/A
Added new unit tests for parsing the configurations
=> Fix MI Durable Task Connections

src/Microsoft.Health.Dicom.SqlServer/Features/Schema/Migrations/28.diff.sql
Fix migration script to unblock deployment. 
- Updated the V28 migration script to drop index which are creating while retrying.
=> Fix migration script

converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj, src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj
Fix prerelease warning for Azure.Monitor.OpenTelemetry.Exporter package
N/A
Pack all the required nuget packages locally.
=> Fix prerelease warning for Azure monitor exporter package

Directory.Packages.props
Reverts microsoft/dicom-server#2331
We'll increment again once the AzureMonitor exporter has been updated
=> Revert "Bump OpenTelemetry from 1.4.0-rc.3 to 1.4.0-rc.4"

Directory.Build.props, Directory.Packages.props, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Microsoft.Health.DicomCast.Core.UnitTests.csproj, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/Microsoft.Health.DicomCast.Hosting.csproj, src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj
The NuGet dependencies for OpenTelemetry do not accurately convey the necessary packages required to run the assembly. Three projects rely on both the `OpenTelemetry` and `OpenTelemetry.Api` NuGet packages, but no project has them properly declared. Furthermore, both the `OpenTelemetry` and ultimately unused `OpenTelemetry.Metrics` NuGet packages are declared in the *Directory.Packages.props* file and yet are not used as `PackageReference` elements in any project.
N/A
PR pipeline and manual validation
=> Fix OpenTelemetry NuGet Dependencies

Microsoft.Health.Dicom.sln
The docker-compose project requires the latest DicomWeb and Functions projects in order to build containers. When this dependency isn't declared, rebuilding the solution can fail on docker-compose.
=> Declare dependencies for docker-compose

src/Microsoft.Health.Dicom.Api.UnitTests/Extensions/MediaTypeHeaderValueExtensionsTests.cs, src/Microsoft.Health.Dicom.Api/Extensions/MediaTypeHeaderValueExtensions.cs, src/Microsoft.Health.Dicom.Web/wwwroot/index.html
Asp.net core/RFC expects request header accept to have quotes in the type like
multipart/related; type="application/octet-stream"; transfer-syntax=*
The new OHIF viewer version and the DICOM standard supports below
multipart/related; type=application/octet-stream; transfer-syntax=*
Put in a hack to handle this in the conversion code.
Added a unit test
=> Support accept type with no quotes

src/Microsoft.Health.Dicom.Api/Logging/TelemetryInitializer.cs
HttpContext is winding down when TelemetryInit is called. when health/check is called, since the version is not there,
it tries to reparse the url, but the services are already winding down.
Handle it gracefully by checking the existing of the routeParam before logging the version.
https://github.com/dotnet/aspnet-api-versioning/blob/435a17ec5001690e531a1715bc736233a2a938db/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningFeature.cs#L34
[AB#101437](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/101437)
health/check does not throw anymore
=> Handle version missing in Telemetry gracefully

src/Microsoft.Health.Dicom.Blob.UnitTests/DicomFileNameWithPrefixTests.cs, src/Microsoft.Health.Dicom.Blob.UnitTests/Features/Export/AzureBlobExportSinkTests.cs, src/Microsoft.Health.Dicom.Blob/Features/Export/AzureBlobExportSink.cs, src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobFileStore.cs, src/Microsoft.Health.Dicom.Blob/Features/Storage/BlobMetadataStore.cs, src/Microsoft.Health.Dicom.Blob/Features/Storage/DicomFileNameWithPrefix.cs, src/Microsoft.Health.Dicom.Blob/Features/Storage/IDicomFileNameBuilder.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/ChangeFeed/ChangeFeedServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Delete/DeleteServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveMetadataServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveResourceServiceTests.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreOrchestratorTests.cs, src/Microsoft.Health.Dicom.Core/Features/ChangeFeed/ChangeFeedService.cs, src/Microsoft.Health.Dicom.Core/Features/Common/IFileStore.cs, src/Microsoft.Health.Dicom.Core/Features/Common/IMetadataStore.cs, src/Microsoft.Health.Dicom.Core/Features/Delete/DeleteService.cs, src/Microsoft.Health.Dicom.Core/Features/Indexing/InstanceReindexer.cs, src/Microsoft.Health.Dicom.Core/Features/Query/QueryService.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/FramesRangeCache.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/IFramesRangeCache.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveMetadataService.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs, src/Microsoft.Health.Dicom.Core/Features/Store/StoreOrchestrator.cs, test/Microsoft.Health.Dicom.Tests.Integration/Features/RetrieveResourceServiceTests.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/DeleteServiceTests.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/FileStoreTests.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/MetadataStoreTests.cs
Since we are using watermark for file name, we don't need VersionedInstanceIdentifier to be passed as an argument. Replaced VersionedInstanceIdentifier to watermark on all the methods
Updated existing unit tests and E2E tests
=> Remove VersionedInstanceIdentifier on blob stores

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/RetrieveResourceServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs, src/Microsoft.Health.Dicom.Tests.Common/Samples.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs
This PR includes changes to support get frame with and without transcoding for both current and original version
Addresses [[AB#102007](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/102007)].
New unit tests and E2E tests are added.
=> Support get frame for both original and current version

build/ci/run-e2e-tests.yml, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExportTests.cs
The Export E2E test in our CI pipeline may have problems creating the blob container if the Azure Storage service takes awhile to complete a deletion. This change will instead use a dynamic blob container name such that we do not need to wait on the sometimes asynchronous deletion of containers.
N/A
Ad-hoc CI: https://microsofthealthoss.visualstudio.com/DicomServer/_build/results?buildId=30935&view=results
=> Fix Export E2E Test Cleanup

src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/OperationsControllerTests.cs, src/Microsoft.Health.Dicom.Api/Controllers/OperationsController.cs
Use `Succeeded` as the completed operation status as recommended in the [Rest API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1325-operation-resource) for V2 and onward.
[AB#94762](https://microsofthealth.visualstudio.com/Health/_workitems/edit/94762/)
New unit tests
=> Use Succeeded for Operation Status in V2

build/ci/run-e2e-tests.yml, src/Microsoft.Health.Dicom.Client/Models/ChangeFeedAction.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExportTests.cs
Use pseudo-random name for export container to avoid delete latency issues when running back-to-back tests on the same container
[AB#103616](https://microsofthealth.visualstudio.com/Health/_workitems/edit/103616)
Ad-hoc CI: https://microsofthealthoss.visualstudio.com/DicomServer/_build/results?buildId=31223&view=results
=> Fix Transient Export Test Failures

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/AcceptHeaderHandlerTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/AcceptHeaderHandler.cs, src/Microsoft.Health.Dicom.Core/Messages/Retrieve/AcceptHeader.cs
SLIM viewer sends multiple accept headers to get frames. Original is the last, this causes us to pick another accept and fail because today our code needs entire file to do transcoding and will throw when file size is greater than 100M.
This fix will make us prioritize picking original if available in the accept list.
https://github.com/ImagingDataCommons/dicom-microscopy-viewer/issues/95
Added unit tests
=> Prioritize original transfer syntax when multiple accepts with no quality provided

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Update/UpdateInstanceOperationServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/Diagnostic/LogForwarderExtensions.cs, src/Microsoft.Health.Dicom.Core/Features/Update/UpdateInstanceOperationService.cs
Enable diagnostic logging for Dicom update
Updated tests
Addresses [103949](https://microsofthealth.visualstudio.com/Health/_workitems/edit/103949)
Manually testing Dicom update feature.
=> Diagnostic logging for Dicom update

test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ChangeFeedTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ChangeFeedTests.cs
Update change feed tests to search for the first event and use its time in the subsequent assertions.
N/A
Locally and via pipelines
=> Improve Change Test Determinism

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Query/QueryServiceTests.cs, src/Microsoft.Health.Dicom.Core/Features/Query/QueryService.cs
Query service used in QIDO request giving a KeyNotFoundException when some of the study instance uids were deleted while the QIDO request is in progress. 
Addresses [issue #105161](https://microsofthealth.visualstudio.com/Health/_workitems/edit/105161).
Manual testing in local environment and added unit test for the edge case
=> Bug in query service causing KeyNotFoundException

converter/dicom-cast/samples/templates/default-azuredeploy.json, converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/ChangeFeedProcessorTests.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Configurations/FeatureConfiguration.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs, converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting/appsettings.json, docs/concepts/dicom-cast.md, samples/templates/dicomcast-fhir-dicom-azuredeploy.json, samples/templates/dicomcast-quick-deploy.json
Customer is experiencing an issue where DICOM Cast will crash when it encounters a DICOM instance that the DicomWebClient is unable to parse. This will add an option to skip instances like that by ignoring JsonExceptions.
Addresses #[105044].
Tested locally
=> Add flag to ignore errors in parsing malformed dicom json

renovate.json
Allow Renovate to update the Ubuntu base image for the SQL dockerfile as long as it uses Focal Fossa
N/A
N/A
=> Update Renovate Config for Focal Ubuntu Base Image in SQL Image

converter/dicom-cast/samples/templates/default-azuredeploy.json, converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json, samples/templates/dicomcast-fhir-dicom-azuredeploy.json, samples/templates/dicomcast-quick-deploy.json
linux_dicom-cast is no longer updated, and dicom-cast image should be used in its place
Addresses [#105670].
=> replace linux_dicom-cast image with dicom-cast

src/Microsoft.Health.Dicom.Core/Features/Workitem/WorkitemDatasetValidatorExtension.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/Audit/AuditTests.Workitem.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkitemTransactionTests.Update.cs
- Make GetReferencedInstancesAndAccessMacroRequirements part of OutputInformationSequence.
- Make ReferencedSOPSequence not mandatory while creating the workitem
There is a discrepancy between [Table CC.2.5-3. UPS SOP Class N-CREATE/N-SET/N-GET/C-FIND Attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_CC.2.5.html#table_CC.2.5-3) and [Table C.30.3-1 specifies the Attributes that describe the performance and results of a Unified Procedure Step (UPS)](https://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.30.html#table_C.30.3-1).
To finalize, Referenced Instances and Access Macro Attributes will be part of Output Information Sequence and not under Unified Procedure Step Performed Procedure Sequence and Output Information Sequence will be under Unified …
=> Make GetReferencedInstancesAndAccessMacroRequirements part of OutputInformationSequence

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Filters/QueryModelStateValidatorAttributeTests.cs, src/Microsoft.Health.Dicom.Api/Features/Filters/QueryModelStateValidatorAttribute.cs, src/Microsoft.Health.Dicom.Core/Exceptions/InvalidQueryStringValuesException.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/WorkItemTransactionTests.Query.cs
Encode string in error message to prevent cross scripting attacks
When validating a frame number passed in as part of the url we check if the input is a valid number. If its not we throw an error message that contains the invalid input that they passed directly. Since we did not encode the response we were susceptible to sending anything malicious back to the user 
_When a web application is vulnerable to this type of attack, it will pass unvalidated input sent through requests to the client. Reflected attacks are delivered to the victim in various ways, such as in an e-mail message, or through some specially crafted URI. When a user is tricked into clicking on the malicious link, the injected code travels to the vulnerable web site, which reflects the attack back to the user’s browser. …
=> Encode String in error message

src/Microsoft.Health.Dicom.Core/Features/Store/StoreOrchestrator.cs
Correctly pass HasFrameMetadata boolean when creating the instance
Addresses [[AB#109143](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/109143)].
=> Pass HasFrameMetadata boolean correctly

src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveRenderedService.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/RetrieveResourceService.cs, src/Microsoft.Health.Dicom.Core/Features/Telemetry/RetrieveMeter.cs
adjusts retrieve metric to track content length as delta, not dimension.
Addresses [[AB#106470](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/106470)].
n/a
=> delta is content length, not dimension

src/Microsoft.Health.Dicom.Core/Features/HealthCheck/BackgroundServiceHealthCheck.cs, src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj
When CMK is misconfigured, BackgroundServiceHealthCheck will fail because the SQL index store is inaccessible.
{"Timestamp":"2023-09-26T22:08:26.4293469+00:00","Level":"Error","MessageTemplate":
"Health check {HealthCheckName} with status {HealthStatus} completed after {ElapsedMilliseconds}ms with message '{HealthCheckDescription}'",
"Properties":{"HealthCheckName":"BackgroundServiceHealthCheck","HealthStatus":"Unhealthy","ElapsedMilliseconds":0.4778,"HealthCheckDescription":"Unhealthy service.","EventId":{"Id":103,"Name":"HealthCheckEnd"},"SourceContext":"Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService","resourceId":"/subscriptions/8ccee270-9421-44ca-bdb5-efa2eceef8dc/resourceGroups/julie-int-demo/providers/Microsoft.HealthcareApis/workspaces/juliedemows/dicomservi …
=> Add cmk validation to background service health check

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs
Handle Task Canceled exception and output 400 instead of 503. Currently when the blob storage is down and the user has canceled the current request, we send 503 instead of 400.
This PR handles the scenario of aggregate exception when one of the innerException is TaskCanceledException.
Addresses [[AB#110186](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/110186)].
Unit test has been for this scenario.
=> Handle Task Canceled exception and output 400 instead of 503

src/Microsoft.Health.Dicom.Azure/Registration/KeyVaultClientRegistrationExtensions.cs, src/Microsoft.Health.Dicom.SqlServer.UnitTests/Microsoft.Health.Dicom.SqlServer.UnitTests.csproj, src/Microsoft.Health.Dicom.SqlServer.UnitTests/Registration/DicomSqlServerRegistrationExtensionsTests.cs, src/Microsoft.Health.Dicom.SqlServer/Registration/DicomSqlServerRegistrationExtensions.cs
- Allow use of explicit workload identity for SQL connections
- Enable configuring retries for Key Vault credentials
[AB#98306](https://microsofthealth.visualstudio.com/Health/_workitems/edit/98306/)
[AB#103496](https://microsofthealth.visualstudio.com/Health/_workitems/edit/103496/)
New unit tests
=> Enable SQL Workload Identity

src/Microsoft.Health.Dicom.Api/Controllers/StoreController.cs, src/Microsoft.Health.Dicom.Api/Features/Conventions/IntroducedInApiVersionAttribute.cs
Allow DICOM update API only in V2
=> Allow DICOM update API only in V2

src/Microsoft.Health.Dicom.SqlServer.UnitTests/Registration/DicomSqlServerRegistrationExtensionsTests.cs, src/Microsoft.Health.Dicom.SqlServer.UnitTests/SqlAuthenticationCollection.cs
Prevent SQL auth tests from running concurrently with other tests due to their manipulation of `static` state
N/A
N/A
=> Disable Test Parallelization for SQL Auth Tests

docs/resources/v2-conformance-statement.md
Update v2-conformance-statement for searching attributes with leniency.
We already specify in QIDO, that only latest wins.  [QIDO Additional Notes](https://github.com/microsoft/dicom-server/blob/main/docs/resources/v2-conformance-statement.md#additional-notes). So there is no update needed.
=> Update v2-conformance-statement for leniency

src/Microsoft.Health.Dicom.SqlServer/Features/Store/SqlIndexDataStoreV37.cs
Throw an InstanceAlreadyExistsException when there is a unique key constraint violation
Addresses [issue #111025](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111025).
Tested manually
=> Fix error message for Unique key violation error

src/Microsoft.Health.Dicom.SchemaManager.Console/Properties/launchSettings.json, src/Microsoft.Health.Dicom.SchemaManager/ApplyCommand.cs, src/Microsoft.Health.Dicom.SchemaManager/CommandCollectionExtensions.cs, src/Microsoft.Health.Dicom.SchemaManager/CommandLineOptions.cs, src/Microsoft.Health.Dicom.SchemaManager/CommandOptions.cs, src/Microsoft.Health.Dicom.SchemaManager/Microsoft.Health.Dicom.SchemaManager.csproj, src/Microsoft.Health.Dicom.SchemaManager/Resources.Designer.cs, src/Microsoft.Health.Dicom.SchemaManager/Resources.resx
Fix usage of the new `--enable-workload-identity` and `-wi` arguments. Without the new option, the arguments are flagged as invalid and the app fails to run
[AB#111048](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111048/)
Tested locally and equivalent changes in PaaS
=> Fix Workload Identity Argument

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/StoreTransactionTestsLatest.cs
Reduce bytes sent for big STOW tests
[AB#111001](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111001)
Ad-hoc PaaS testing
=> Slightly Reduce Size of E2E Tests to Provide ~100 MB Clearance 

src/Microsoft.Health.Dicom.SqlServer/Features/Partitioning/SqlPartitionStoreV6.cs, test/Microsoft.Health.Dicom.Tests.Integration/Persistence/PartitionTests.cs
Handle the case when  sql throws 2601 error code meaning a race condition where a process tries to insert a partition key which already exists.
Addresses [issue #110438](https://microsofthealth.visualstudio.com/Health/_workitems/edit/110438)
Manually tested. Also updated integration test.
=> Handle unique constraint voilation

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/StoreTransactionTestsLatest.cs
Reduce the size of the 2 GB test to ~1.70 GB to allow for chunking the request as `Content-Length` is not specified to save on memory
N/A
N/A
=> Reduce Size of STOW Test to Accommodate Chunking

docs/resources/conformance-statement.md, docs/resources/v2-conformance-statement.md, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/AcceptHeaderHandlerTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/AcceptHeaderHandler.cs, src/Microsoft.Health.Dicom.Core/Web/KnownContentTypes.cs, test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Frame.cs
Currently OHIF microscopic viewer, retrieves frames using `*/*` as accept header. The currently implementation, throws exception since we don't support. 
This PR adds support for retrieving frames/instance using `*/*` mediatype. Depends on the resourceType defaults are choosen.
Defaults are choosen as per the standard. 
Default MediaType - https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4.4
Default TransferSyntaxUID - https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.3.1
Addresses [AB#112103].
- New unit test and E2E test are added
=> Add support to */* mediatype

src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ChangeFeed/SqlChangeFeedStoreV39.cs, src/Microsoft.Health.Dicom.SqlServer/Features/ExtendedQueryTag/SqlExtendedQueryTagStoreV36.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Partitioning/SqlPartitionStoreV6.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Query/SqlQueryStoreV27.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Retrieve/SqlInstanceStoreV34.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Retrieve/SqlInstanceStoreV46.cs, src/Microsoft.Health.Dicom.SqlServer/Features/Workitem/SqlWorkitemStoreV22.cs
Wrap SQL Exception in DataStoreException to handle TaskCanceled exception as BadRequest.
AB#112589, AB#112741, AB#112755 
Existing test was executed
=> Wrap SQL Exception in DataStoreException

docs/resources/conformance-statement.md, docs/resources/v2-conformance-statement.md, src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/AcceptHeaderHandlerTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/AcceptHeaderHandler.cs
Use original transfer syntax for */* accept header
DICOM standard - https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7
Addresses [AB#112103].
=> Use original transfer syntax for */* accept header

src/Microsoft.Health.Dicom.Api.UnitTests/Features/Exceptions/ExceptionHandlingMiddlewareTests.cs, src/Microsoft.Health.Dicom.Api/Features/Exceptions/ExceptionHandlingMiddleware.cs
Catch msft health exceptions where the inner exception is OperationCanceledException (TaskCanceledException derives from this)
Addresses [113536].
Added new unit tests
=> Catch operation cancelled inner exceptions in middleware

test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/UpdateInstanceTests.cs
Fix update test to use different value for extended query tag
=> Fix update test to use different value for extended query tag

src/Microsoft.Health.Dicom.Api/Modules/SecurityModule.cs
Set DefaultMapInboundClaims to false to keep roles claim type.
With .net 8, the roles claim is removed from the Principal identity. Setting DefaultMapInboundClaims to false will keep the claim as is.
=> Set DefaultMapInboundClaims to false to keep roles claim type

Directory.Build.props, Directory.Packages.props, renovate.json, src/Microsoft.Health.Dicom.WebUtilities/Microsoft.Health.Dicom.WebUtilities.csproj
Update some packages, including some like OTel which must only be updated for .NET 8 as it relies upon v8 versions of the Microsoft.Extensions.* libraries.
N/A
Existing test suites
=> Update Pkgs for .NET 8

src/Microsoft.Health.Dicom.Api.UnitTests/Features/BackgroundServices/DeletedInstanceCleanupWorkerTests.cs, src/Microsoft.Health.Dicom.Api/Features/BackgroundServices/DeletedInstanceCleanupWorker.cs
When we see CMK misconfigurations, the delete instance background worker will either:
1. Throw a DataStoreNotReadyException. There is no polling wait in the while loop here, so this will log infinitely until we are throttled, which will kill the pod (at least I think so, its hard to see the behavior here because its overwhelmed with logs
2. Throw a CMK specific exception, which is not handled specially and logged as a critical error.
Ex: {"Timestamp":"2023-12-20T05:08:31.4623481+00:00","Level":"Fatal","MessageTemplate":"Unhandled exception in the deleted instance cleanup worker.","Exception":"Microsoft.Data.SqlClient.SqlException (0x80131904): Can not connect to the database in its current state.\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject …
=> Do not log cmk errors at critical level

src/Microsoft.Health.Dicom.Core.UnitTests/Features/Retrieve/AcceptHeaderHandlerTests.cs, src/Microsoft.Health.Dicom.Core/Features/Retrieve/AcceptHeaderHandler.cs, src/Microsoft.Health.Dicom.Web/appsettings.json, src/Microsoft.Health.Dicom.Web/wwwroot/app-config.js
This PR includes 2 changes
1. Use multipart related payload type for */*, since viewers works very well with multipart
2. Update the OHIF app.config to use original transfer syntax (*)
3. Enable dicom upload
4. Enable OHIF viewer 
Manually tested with OHIF viewer.
=> Use multipart for any mediaType and for OHIF use original transfer syntax

src/Microsoft.Health.Dicom.Blob/Features/Health/DicomConnectedStoreHealthCheck.cs
Add log to health check. Helps confirm health check is running and that the dicom has connected store enabled
=> Add log to connected store health check

src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs, src/Microsoft.Health.Dicom.Blob/Features/ExternalStore/ExternalStoreHealthExpiryHttpPipelinePolicy.cs, src/Microsoft.Health.Dicom.Blob/Registration/DicomServerBuilderBlobRegistrationExtensions.cs, src/Microsoft.Health.Dicom.Core/Configs/FeatureConfiguration.cs, src/Microsoft.Health.Dicom.Core/Configs/HealthCheckPublisherConfiguration.cs, src/Microsoft.Health.Dicom.Web/appsettings.json
Add configuration to filter health checks. Any health check can be added to this list, and it will be excluded from running. 
Also fixed an issue with running the IDP health check locally - the http pipeline policy required a blob URI to run, which does not exist when running with Azurite
Addresses #115147
Ran locally. Added single & multiple health check names to the list and saw that they were removed from execution. Also tried removing the config all together or using an empty list, in which case all of the health checks will run.
=> Add configuration to filter health checks

forks/Microsoft.Health.FellowOakDicom/Serialization/JsonDicomConverter.cs, src/Microsoft.Health.Dicom.Core.UnitTests/Serialization/JsonDicomConverterExtendedTests.cs
Catch OverflowException when converting an VR IS to an integer. [Fo-dicom PR](https://github.com/fo-dicom/fo-dicom/pull/1522) for reference.
Addresses [issue #111029](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111029), [issue #111027](https://microsofthealth.visualstudio.com/Health/_workitems/edit/111027).
Added unit tests for invalid, overflow and floating point numbers
=> Handle OverflowException when converting an VR IS to an integer

tools/dicom-web-electron/main.js
Suppress validation warning
[[AB#134140](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/134140)]
=> Suppress validation warning
